import React, { useState, useEffect } from 'react';
import {
  Globe2,
  MapPin,
  Clock,
  ShieldCheck,
  Phone,
  MessageCircle,
  FileText,
  DollarSign,
  Package,
  Layers,
  ChevronRight,
  Sparkles,
  Search,
  SlidersHorizontal,
  CheckCircle2,
  Download,
  Printer,
  X,
  Leaf,
  Ruler,
  Tag,
  Barcode,
  HelpCircle,
  PenTool,
  Check,
  Edit3,
  Save,
  Lock,
  Mail,
  Send,
  ShieldAlert,
  FileCode,
  Truck,
  Plane,
  Star,
  Plus,
  ThumbsUp,
  Award,
  Filter,
  ExternalLink,
  Building,
  UserCheck,
  RotateCcw
} from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export interface SupplierReview {
  id: string;
  supplierId: string;
  authorName: string;
  authorCompany: string;
  ratingQuality: number;
  ratingDelivery: number;
  ratingSupport: number;
  ratingPrice: number;
  overallRating: number;
  title: string;
  comment: string;
  isVerifiedBuyer: boolean;
  wouldRecommend: boolean;
  date: string;
}

export interface Supplier {
  id: string;
  name: string;
  country: string;
  flag: string;
  city: string;
  category: 'fashion' | 'furniture' | 'footwear' | 'bags' | 'packaging' | 'hardware' | 'textile';
  categoryLabel: string;
  defaultLang: 'pt' | 'tr' | 'es' | 'it' | 'en' | 'fr' | 'zh';
  moq: number;
  leadTime: string;
  pricePerUnit: number;
  rating: number;
  reviewsCount: number;
  certifications: string[];
  specialty: string;
  whatsapp: string;
  email?: string;
  website?: string;
  image: string;
  isUserAdded?: boolean;
}

export type TechPackLanguage = 'en' | 'pt' | 'tr' | 'es' | 'it';

const TECHPACK_I18N: Record<TechPackLanguage, Record<string, string>> = {
  en: {
    docTitle: 'OFFICIAL PRODUCTION TECH PACK & SPECIFICATION',
    docRev: 'REV 3.4 • AUDITABLE FACTORY STANDARD',
    styleLabel: 'Style / Garment Name:',
    factoryLabel: 'Contracted Factory:',
    volumeLabel: 'PO Volume:',
    pantoneLabel: 'Pantone TCX Colors:',
    gradingTitle: '1. SIZING TABLE & GRADING SPECIFICATION',
    tolerance: 'Tolerance: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Point of Measure (POM)',
    baseSample: 'M (Base Sample)',
    chest: 'Chest Width (2.5cm below armhole)',
    length: 'Body Length (from High Point Shoulder)',
    sleeve: 'Raglan Sleeve Length (from Center Back)',
    hem: 'Bottom Hem Opening / Waist',
    commercialTitle: '2. COMMERCIAL TERMS, INCOTERMS & QUALITY PROTOCOL',
    incotermLabel: 'Commercial Incoterm 2020:',
    incotermDesc: 'FOB (Free On Board) Port of Origin or DDP (Delivered Duty Paid to client warehouse).',
    paymentLabel: 'Payment Milestones:',
    paymentDesc: '30% Deposit upon PO approval + 70% Balance against AQL 2.5 final inspection before dispatch.',
    ppsLabel: 'Pre-Production Sample (PPS):',
    ppsDesc: '1 Physical sample required within 7 business days for fit approval prior to bulk cutting.',
    bomTitle: '3. BILL OF MATERIALS (BOM) & STITCHING STANDARD',
    shellLabel: 'Shell Fabric:',
    shellDesc: '100% Nylon Ripstop 240 GSM with DWR water-repellent coating and matte anti-tear finish.',
    zipperLabel: 'Zippers & Trims:',
    zipperDesc: 'YKK Aquaguard #5 waterproof zippers with embossed matte silicone pullers.',
    stitchLabel: 'Stitch Density (SPI):',
    stitchDesc: 'Bonded poly 60/2 thread with 12 Stitches Per Inch (12 SPI) and Bar-Tack reinforcements.',
    careLabel: 'Care Instructions:',
    careDesc: 'Machine wash 30°C delicate, do not bleach, low iron max 110°C, do not dry clean.',
    signaturesTitle: '4. FORMAL APPROVAL SIGNATURES & LEGAL CONFORMITY',
    brandSig: 'Brand Creative Director Approval:',
    factorySig: 'Factory Production Plant Manager:',
    signDate: 'Signature & Date: ____________________',
    footerNotice: 'Official auditable document generated by Aether Synergy • Factory Legal Acceptance',
    printBtn: 'Print / Save Official PDF',
    editBtn: 'Edit Tech Pack',
    saveBtn: 'Save Changes'
  },
  pt: {
    docTitle: 'FICHA TÉCNICA OFICIAL DE PRODUÇÃO INDUSTRIAL',
    docRev: 'REV 3.4 • PADRÃO DE CONFECÇÃO AUDITÁVEL',
    styleLabel: 'Nome do Modelo / Peça:',
    factoryLabel: 'Fábrica Contratada:',
    volumeLabel: 'Volume de Produção:',
    pantoneLabel: 'Cores Pantone TCX:',
    gradingTitle: '1. TABELA DE MEDIDAS E GRADUAÇÃO INDUSTRIAL',
    tolerance: 'Tolerância: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Ponto de Medida (POM)',
    baseSample: 'M (Amostra Base)',
    chest: 'Largura do Peito (2.5cm abaixo da cava)',
    length: 'Comprimento Total (do ponto mais alto do ombro)',
    sleeve: 'Manga Raglan (do centro das costas)',
    hem: 'Abertura da Bainha / Cintura',
    commercialTitle: '2. TERMOS COMERCIAIS, INCOTERMS E PROTOCOLO DE QUALIDADE',
    incotermLabel: 'Incoterm Comercial 2020:',
    incotermDesc: 'FOB (Free On Board) Porto de Origem ou DDP (Entrega com impostos pagos no destino).',
    paymentLabel: 'Condições de Pagamento:',
    paymentDesc: '30% Sinal na aprovação da Ordem + 70% Saldo após inspeção final de qualidade AQL 2.5.',
    ppsLabel: 'Amostra Pré-Produção (PPS):',
    ppsDesc: '1 Amostra física requerida em até 7 dias úteis para aprovação de modelagem antes do corte.',
    bomTitle: '3. LISTA DE MATERIAIS (BOM) E PADRÃO DE COSTURA',
    shellLabel: 'Tecido Principal:',
    shellDesc: '100% Poliamida Ripstop 240 GSM com acabamento DWR repelente a água e toque mate anti-rasgo.',
    zipperLabel: 'Zíperes e Aviamentos:',
    zipperDesc: 'Zíperes YKK Aquaguard #5 impermeáveis com puxadores personalizados em silicone.',
    stitchLabel: 'Densidade de Pontos (SPI):',
    stitchDesc: 'Linha bonderizada 60/2 com 12 pontos por polegada (12 SPI) e travetes de reforço.',
    careLabel: 'Instruções de Lavagem:',
    careDesc: 'Lavagem suave na máquina 30°C, não usar alvejante, passar a ferro até 110°C.',
    signaturesTitle: '4. ASSINATURAS FORMAIS DE APROVAÇÃO E CONFORMIDADE',
    brandSig: 'Aprovação Diretor Criativo Marca:',
    factorySig: 'Aprovação Gerente de Produção Fábrica:',
    signDate: 'Assinatura e Data: ____________________',
    footerNotice: 'Documento oficial gerado por Aether Synergy • Aceitação Legal da Fábrica',
    printBtn: 'Imprimir / Salvar PDF Oficial',
    editBtn: 'Editar Ficha Técnica',
    saveBtn: 'Salvar Alterações'
  },
  tr: {
    docTitle: 'RESMİ ENDÜSTRİYEL İMALAT TEKNİK ŞARTNAMESİ',
    docRev: 'REV 3.4 • DENETLENEBİLİR FABRİKA STANDARDI',
    styleLabel: 'Model / Ürün Adı:',
    factoryLabel: 'Sözleşmeli Fabrika:',
    volumeLabel: 'Sipariş Adedi:',
    pantoneLabel: 'Pantone TCX Renk Kodları:',
    gradingTitle: '1. ÖLÇÜ TABLOSU VE SERİLEME ŞARTNAMESİ',
    tolerance: 'Tolerans: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Ölçüm Noktası (POM)',
    baseSample: 'M (Numune Beden)',
    chest: 'Göğüs Genişliği (Koltuk altından 2.5cm)',
    length: 'Beden Boyu (Omuz yüksek noktasından)',
    sleeve: 'Reglan Kol Boyu (Arka ortadan)',
    hem: 'Etek Ucu / Bel Genişliği',
    commercialTitle: '2. TİCARİ ŞARTLAR, INCOTERMS VE KALİTE KONTROL',
    incotermLabel: 'Teslim Şekli (Incoterm 2020):',
    incotermDesc: 'FOB (Free On Board) Çıkış Limanı veya DDP (Gümrük vergileri ödenmiş teslimat).',
    paymentLabel: 'Ödeme Koşulları:',
    paymentDesc: '%30 Sipariş onayı ile Peşinat + %70 AQL 2.5 son kalite kontrolü sonrası sevk öncesi.',
    ppsLabel: 'İmalat Öncesi Numune (PPS):',
    ppsDesc: 'Kumaş kesiminden önce kalıp onayı için 7 iş günü içinde 1 adet onay numunesi.',
    bomTitle: '3. MALZEME LİSTESİ (BOM) VE DİKİŞ STANDARDI',
    shellLabel: 'Dış Kumaş:',
    shellDesc: '%100 Naylon Ripstop 240 GSM, DWR su itici kaplamalı ve mat yırtılmaz dokuma.',
    zipperLabel: 'Fermuar ve Aksesuarlar:',
    zipperDesc: 'YKK Aquaguard #5 su geçirmez fermuarlar ve özel silikon elcikler.',
    stitchLabel: 'Dikiş Sıklığı (SPI):',
    stitchDesc: 'İnç başına 12 dikiş (12 SPI) ve kritik noktalarda Bar-Tack punteriz takviyesi.',
    careLabel: 'Yıkama Talimatları:',
    careDesc: '30°C hassas makine yıkama, ağartıcı kullanılmaz, düşük ısıda maks 110°C ütüleme.',
    signaturesTitle: '4. RESMİ ONAY İMZALARI VE TEKNİK UYGUNLUK',
    brandSig: 'Marka Kreatif Direktörü Onayı:',
    factorySig: 'Fabrika Üretim ve Kalite Müdürü:',
    signDate: 'İmza ve Tarih: ____________________',
    footerNotice: 'Aether Synergy tarafından oluşturulan resmi teknik şartname belgesi',
    printBtn: 'Yazdır / PDF Olarak Kaydet',
    editBtn: 'Şartnameyi Düzenle',
    saveBtn: 'Değişiklikleri Kaydet'
  },
  it: {
    docTitle: 'SCHEDA TECNICA DI PRODUZIONE INDUSTRIALE',
    docRev: 'REV 3.4 • STANDARD AUDITABILE PER LA MANIFATTURA',
    styleLabel: 'Stile / Nome Capo:',
    factoryLabel: 'Fabbrica Assegnata:',
    volumeLabel: 'Volume Ordine:',
    pantoneLabel: 'Colori Pantone TCX:',
    gradingTitle: '1. TABELLA MISURE E GRADAZIONE INDUSTRIALE',
    tolerance: 'Tolleranza: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Punto di Misura (POM)',
    baseSample: 'M (Campione Base)',
    chest: 'Larghezza Torace (2.5cm sotto giromanica)',
    length: 'Lunghezza Totale (da punto spalla HPS)',
    sleeve: 'Manica Raglan (da centro schiena)',
    hem: 'Fondo / Larghezza Bacino',
    commercialTitle: '2. TERMINI COMMERCIALI, INCOTERMS E QUALITÀ',
    incotermLabel: 'Incoterm Commerciale 2020:',
    incotermDesc: 'FOB (Free On Board) Porto di Partenza o DDP (Reso Sdoganato a destinazione).',
    paymentLabel: 'Termini di Pagamento:',
    paymentDesc: '30% Anticipo all\'ordine + 70% Saldo previa ispezione finale di qualità AQL 2.5.',
    ppsLabel: 'Campione Pre-Produzione (PPS):',
    ppsDesc: '1 Prototipo fisico richiesto entro 7 giorni lavorativi per approvazione fitting prima del taglio.',
    bomTitle: '3. DISTINTA BASE (BOM) E STANDARD DI CUCITURA',
    shellLabel: 'Tessuto Esterno:',
    shellDesc: '100% Nylon Ripstop 240 GSM con finitura idrorepellente DWR e mano opaca antistrappo.',
    zipperLabel: 'Zip e Accessori:',
    zipperDesc: 'Zip termonastrate YKK Aquaguard #5 impermeabili con tiretti in silicone personalizzati.',
    stitchLabel: 'Densità di Cucitura (SPI):',
    stitchDesc: 'Filato 60/2 con 12 punti per pollice (12 SPI) e travette di rinforzo Bar-Tack.',
    careLabel: 'Istruzioni di Lavaggio:',
    careDesc: 'Lavaggio in lavatrice 30°C ciclo delicato, non candeggiare, stiro max 110°C.',
    signaturesTitle: '4. FIRME UFFICIALI DI APPROVAZIONE E CONFORMITÀ',
    brandSig: 'Approvazione Direttore Creativo Brand:',
    factorySig: 'Approvazione Direttore di Produzione Fabbrica:',
    signDate: 'Firma e Data: ____________________',
    footerNotice: 'Documento ufficiale generato da Aether Synergy • Accettazione Legale Manifattura',
    printBtn: 'Stampa / Salva PDF Ufficiale',
    editBtn: 'Modifica Scheda Tecnica',
    saveBtn: 'Salva Modifiche'
  },
  es: {
    docTitle: 'FICHA TÉCNICA OFICIAL DE PRODUCCIÓN INDUSTRIAL',
    docRev: 'REV 3.4 • ESTÁNDAR AUDITABLE DE CONFECCIÓN',
    styleLabel: 'Estilo / Prenda:',
    factoryLabel: 'Fábrica Asignada:',
    volumeLabel: 'Volumen de Orden:',
    pantoneLabel: 'Colores Pantone TCX:',
    gradingTitle: '1. TABLA DE MEDIDAS & GRADACIÓN INDUSTRIAL',
    tolerance: 'Tolerancia: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Punto de Medida (POM)',
    baseSample: 'M (Muestra Base)',
    chest: 'Ancho de Pecho (2.5cm bajo sisa)',
    length: 'Largo Total (desde HPS)',
    sleeve: 'Largo de Manga Raglán (desde centro espalda)',
    hem: 'Ancho de Ruedo / Cintura',
    commercialTitle: '2. TÉRMINOS COMERCIALES, INCOTERMS & PROTOCOLO DE CALIDAD',
    incotermLabel: 'Término Comercial (Incoterm 2020):',
    incotermDesc: 'FOB (Free On Board) Puerto de Origen o DDP (Entregado en almacén destino con aranceles pagados).',
    paymentLabel: 'Condiciones de Pago:',
    paymentDesc: '30% Anticipo al aprobar Orden de Compra + 70% Saldo contra inspección final AQL 2.5 previa al despacho.',
    ppsLabel: 'Muestra Pre-Producción (PPS):',
    ppsDesc: '1 Prototipo físico (PPS) debe enviarse en 7 días hábiles para aprobación de calce antes del corte en serie.',
    bomTitle: '3. LISTA DE MATERIALES (BOM) & NORMAS DE COSTURA',
    shellLabel: 'Tejido Exterior:',
    shellDesc: '100% Nylon Ripstop 240 GSM con recubrimiento DWR repelente al agua y acabado mate anti-desgarro.',
    zipperLabel: 'Cremalleras & Herrajes:',
    zipperDesc: 'YKK Aquaguard #5 impermeables con tiradores de silicona negra grabados con logo Aether.',
    stitchLabel: 'Densidad de Costura (SPI):',
    stitchDesc: 'Hilo bondeado 60/2 con 12 puntadas por pulgada (12 SPI) y remates Bar-Tack en zonas de carga.',
    careLabel: 'Instrucciones de Lavado:',
    careDesc: 'Lavado a máquina 30°C ciclo suave, no usar cloro, planchar a temperatura baja (máx 110°C).',
    signaturesTitle: '4. FIRMAS DE APROBACIÓN Y CONFORMIDAD TÉCNICA',
    brandSig: 'Director Creativo / Marca:',
    factorySig: 'Gerente de Planta / Fábrica:',
    signDate: 'Firma & Fecha: ____________________',
    footerNotice: 'Documento oficial generado por Aether Synergy • Válido para producción internacional',
    printBtn: 'Imprimir / Guardar PDF Oficial',
    editBtn: 'Editar Ficha Técnica',
    saveBtn: 'Guardar Cambios'
  }
};

const BASE_SUPPLIERS: Supplier[] = [
  {
    id: 'pt-porto-textiles',
    name: 'Porto Luxury Garments S.A.',
    country: 'Portugal',
    flag: '🇵🇹',
    city: 'Oporto',
    category: 'fashion',
    categoryLabel: '👗 Moda & Confección',
    defaultLang: 'pt',
    moq: 100,
    leadTime: '18 - 24 días',
    pricePerUnit: 24.50,
    rating: 4.9,
    reviewsCount: 38,
    certifications: ['GOTS Orgánico', 'OEKO-TEX 100', 'ISO 9001'],
    specialty: 'Algodón francés pesado 460 GSM, confección techwear premium y teñidos ecológicos.',
    whatsapp: '+351912345678',
    email: 'production@portoluxurytextiles.pt',
    website: 'https://portoluxurytextiles.pt',
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'tr-istanbul-craft',
    name: 'Bosphorus Apparel & Denim Ltd.',
    country: 'Turquía',
    flag: '🇹🇷',
    city: 'Estambul',
    category: 'fashion',
    categoryLabel: '👗 Moda & Streetwear',
    defaultLang: 'tr',
    moq: 150,
    leadTime: '15 - 20 días',
    pricePerUnit: 18.20,
    rating: 4.8,
    reviewsCount: 45,
    certifications: ['OEKO-TEX 100', 'BSCI Audited'],
    specialty: 'Tejido técnico repelente al agua, lavados vintage y cremalleras selladas.',
    whatsapp: '+905321234567',
    email: 'b2b@bosphorusdenim.tr',
    image: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'co-medellin-textiles',
    name: 'Andes Fabric & Tech S.A.S.',
    country: 'Colombia',
    flag: '🇨🇴',
    city: 'Medellín',
    category: 'fashion',
    categoryLabel: '👗 Moda & Streetwear',
    defaultLang: 'es',
    moq: 80,
    leadTime: '12 - 16 días',
    pricePerUnit: 14.80,
    rating: 4.9,
    reviewsCount: 62,
    certifications: ['Fair Trade', 'GOTS Orgánico', 'Carbon Neutral'],
    specialty: 'Ropa urbana oversized, bordados de alta densidad y confección ágil para marcas emergentes.',
    whatsapp: '+573001234567',
    email: 'contacto@andestextil.co',
    website: 'https://andestextil.co',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'it-milan-atelier',
    name: 'Atelier Sartoriale Milano',
    country: 'Italia',
    flag: '🇮🇹',
    city: 'Milán',
    category: 'fashion',
    categoryLabel: '👗 Alta Costura & Sastrería',
    defaultLang: 'it',
    moq: 50,
    leadTime: '25 - 30 días',
    pricePerUnit: 48.00,
    rating: 5.0,
    reviewsCount: 29,
    certifications: ['Made in Italy Certified', 'B-Corp', 'OEKO-TEX 100'],
    specialty: 'Sastrería contemporánea, cueros de curtiduría toscana y piezas de pasarela.',
    whatsapp: '+390212345678',
    email: 'atelier@sartorialemilano.it',
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'mx-leon-footwear',
    name: 'León Leather Craft & Sole Foundry',
    country: 'México',
    flag: '🇲🇽',
    city: 'León, Guanajuato',
    category: 'footwear',
    categoryLabel: '👟 Calzado & Marroquinería',
    defaultLang: 'es',
    moq: 60,
    leadTime: '14 - 18 días',
    pricePerUnit: 22.00,
    rating: 4.9,
    reviewsCount: 51,
    certifications: ['Leather Working Group (LWG Gold)', 'ISO 9001'],
    specialty: 'Botas de cuero vacuno flor, sneakers urbanos y moldes de inyección de suelas EVA.',
    whatsapp: '+524771234567',
    email: 'ventas@leonleathercraft.mx',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'es-valencia-furniture',
    name: 'Iberia Wood & CNC Upholstery S.L.',
    country: 'España',
    flag: '🇪🇸',
    city: 'Valencia',
    category: 'furniture',
    categoryLabel: '🪑 Mobiliario & Tapicería',
    defaultLang: 'es',
    moq: 25,
    leadTime: '20 - 25 días',
    pricePerUnit: 85.00,
    rating: 4.9,
    reviewsCount: 22,
    certifications: ['FSC Sostenible', 'PEFC Madera', 'ISO 14001'],
    specialty: 'Sillas nórdicas en madera curvada de roble, mecanizado CNC 5 ejes y tapicería en piel.',
    whatsapp: '+34961234567',
    email: 'info@iberiawoodcraft.es',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'cn-shenzhen-packaging',
    name: 'Shenzhen Precision Die-Cut & Trims Ltd.',
    country: 'China',
    flag: '🇨🇳',
    city: 'Shenzhen',
    category: 'packaging',
    categoryLabel: '📦 Packaging & Herrajes',
    defaultLang: 'en',
    moq: 500,
    leadTime: '10 - 15 días',
    pricePerUnit: 1.85,
    rating: 4.7,
    reviewsCount: 88,
    certifications: ['ISO 9001', 'FSC Recycled', 'RoHS'],
    specialty: 'Cajas rígidas magnéticas, troquelado Fefco, cremalleras impermeables y tiradores metálicos.',
    whatsapp: '+8675512345678',
    email: 'export@szprecisionpackaging.cn',
    image: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=500&auto=format&fit=crop&q=80'
  },
  {
    id: 'pe-lima-pima',
    name: 'Cusco & Lima Pima Cotton Mills',
    country: 'Perú',
    flag: '🇵🇪',
    city: 'Lima',
    category: 'textile',
    categoryLabel: '🧵 Telas & Algodón Pima',
    defaultLang: 'es',
    moq: 100,
    leadTime: '14 - 20 días',
    pricePerUnit: 16.50,
    rating: 5.0,
    reviewsCount: 34,
    certifications: ['GOTS Orgánico', 'Fair Trade Certified', 'Oeko-Tex Standard'],
    specialty: 'Algodón Pima peruano 100% fibra larga, camisetas premium y hoodies de tacto sedoso.',
    whatsapp: '+51987654321',
    email: 'contacto@limapimacotton.pe',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=500&auto=format&fit=crop&q=80'
  }
];

const INITIAL_REVIEWS: SupplierReview[] = [
  {
    id: 'rev-01',
    supplierId: 'co-medellin-textiles',
    authorName: 'Carlos Mendoza',
    authorCompany: 'Aether Cyberwear Labs',
    ratingQuality: 5,
    ratingDelivery: 5,
    ratingSupport: 5,
    ratingPrice: 4.8,
    overallRating: 4.95,
    title: 'Excelente calidad en algodón 460 GSM y bordados 3D',
    comment: 'Trabajamos un lote de 300 hoodies con ellos. La muestra PPS llegó en solo 4 días a Bogotá y la producción final superó el control de calidad AQL 2.5 sin una sola falla de costura.',
    isVerifiedBuyer: true,
    wouldRecommend: true,
    date: '15 Ago 2026'
  },
  {
    id: 'rev-02',
    supplierId: 'pt-porto-textiles',
    authorName: 'Sophie Van Der Bilt',
    authorCompany: 'Nordic Studio Amsterdam',
    ratingQuality: 5,
    ratingDelivery: 4.8,
    ratingSupport: 5,
    ratingPrice: 4.7,
    overallRating: 4.9,
    title: 'La mejor fábrica de Europa para streetwear de lujo',
    comment: 'Los acabados en French Terry y los tintes reactivos son de nivel pasarela. Comunicación impecable por WhatsApp y envío DDP directo a nuestro almacén.',
    isVerifiedBuyer: true,
    wouldRecommend: true,
    date: '02 Sep 2026'
  }
];

const STORAGE_KEY_CUSTOM_SUPPLIERS = 'aether_user_custom_suppliers_v1';
const STORAGE_KEY_REVIEWS = 'aether_suppliers_reviews_v1';

export const GlobalSuppliers: React.FC = () => {
  const { user } = useAuth();

  // Suppliers & Reviews State with Persistence
  const [suppliers, setSuppliers] = useState<Supplier[]>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY_CUSTOM_SUPPLIERS);
      if (stored) {
        const parsed = JSON.parse(stored);
        return [...BASE_SUPPLIERS, ...parsed];
      }
    } catch (e) {
      console.error(e);
    }
    return BASE_SUPPLIERS;
  });

  const [reviews, setReviews] = useState<SupplierReview[]>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY_REVIEWS);
      if (stored) return JSON.parse(stored);
    } catch (e) {
      console.error(e);
    }
    return INITIAL_REVIEWS;
  });

  const [selectedSupplier, setSelectedSupplier] = useState<Supplier>(suppliers[0]);
  const [orderQuantity, setOrderQuantity] = useState<number>(250);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCountry, setSelectedCountry] = useState('all');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [selectedCert, setSelectedCert] = useState('all');

  // Modals State
  const [isTechPackModalOpen, setIsTechPackModalOpen] = useState(false);
  const [isRFQModalOpen, setIsRFQModalOpen] = useState(false);
  const [isFreightModalOpen, setIsFreightModalOpen] = useState(false);
  const [isAddSupplierModalOpen, setIsAddSupplierModalOpen] = useState(false);
  const [isRateSupplierModalOpen, setIsRateSupplierModalOpen] = useState(false);
  const [isReviewsDrawerOpen, setIsReviewsDrawerOpen] = useState(false);

  // New Supplier Form State
  const [newSupName, setNewSupName] = useState('');
  const [newSupCountry, setNewSupCountry] = useState('Colombia');
  const [newSupFlag, setNewSupFlag] = useState('🇨🇴');
  const [newSupCity, setNewSupCity] = useState('');
  const [newSupCategory, setNewSupCategory] = useState<any>('fashion');
  const [newSupMoq, setNewSupMoq] = useState(100);
  const [newSupLeadTime, setNewSupLeadTime] = useState('15 - 20 días');
  const [newSupPrice, setNewSupPrice] = useState(18.00);
  const [newSupWhatsapp, setNewSupWhatsapp] = useState('');
  const [newSupEmail, setNewSupEmail] = useState('');
  const [newSupWebsite, setNewSupWebsite] = useState('');
  const [newSupSpecialty, setNewSupSpecialty] = useState('');
  const [newSupCerts, setNewSupCerts] = useState('OEKO-TEX 100, ISO 9001');

  // New Rating Form State
  const [rateQuality, setRateQuality] = useState(5);
  const [rateDelivery, setRateDelivery] = useState(5);
  const [rateSupport, setRateSupport] = useState(5);
  const [ratePrice, setRatePrice] = useState(5);
  const [reviewTitle, setReviewTitle] = useState('');
  const [reviewComment, setReviewComment] = useState('');
  const [wouldRecommend, setWouldRecommend] = useState(true);

  // Tech Pack Language
  const [techPackLang, setTechPackLang] = useState<TechPackLanguage>('en');

  // Filter logic
  const filteredSuppliers = suppliers.filter((s) => {
    const matchSearch =
      s.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      s.specialty.toLowerCase().includes(searchQuery.toLowerCase()) ||
      s.city.toLowerCase().includes(searchQuery.toLowerCase());
    const matchCountry = selectedCountry === 'all' || s.country.toLowerCase() === selectedCountry.toLowerCase();
    const matchCategory = selectedCategory === 'all' || s.category === selectedCategory;
    const matchCert = selectedCert === 'all' || s.certifications.some((c) => c.toLowerCase().includes(selectedCert.toLowerCase()));
    return matchSearch && matchCountry && matchCategory && matchCert;
  });

  const activeSupplier = selectedSupplier || suppliers[0];
  const activeSupplierReviews = reviews.filter((r) => r.supplierId === activeSupplier.id);

  // Financial calculations
  const totalProductionCost = activeSupplier.pricePerUnit * orderQuantity;
  const estimatedShippingAir = Math.round(orderQuantity * 3.2);
  const estimatedCustoms = Math.round(totalProductionCost * 0.08);
  const grandTotalCost = totalProductionCost + estimatedShippingAir + estimatedCustoms;
  const costPerPieceLanded = (grandTotalCost / orderQuantity).toFixed(2);

  // Save new Supplier handler
  const handleSaveNewSupplier = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newSupName.trim() || !newSupCity.trim()) {
      alert('Ingresa el nombre de la empresa y la ciudad.');
      return;
    }

    const createdSupplier: Supplier = {
      id: 'custom-sup-' + Date.now(),
      name: newSupName.trim(),
      country: newSupCountry,
      flag: newSupFlag,
      city: newSupCity.trim(),
      category: newSupCategory,
      categoryLabel: newSupCategory === 'fashion' ? '👗 Moda & Confección' : newSupCategory === 'footwear' ? '👟 Calzado' : newSupCategory === 'furniture' ? '🪑 Mobiliario' : '📦 Packaging & Herrajes',
      defaultLang: 'es',
      moq: Number(newSupMoq) || 50,
      leadTime: newSupLeadTime || '15 - 20 días',
      pricePerUnit: Number(newSupPrice) || 20.00,
      rating: 5.0,
      reviewsCount: 1,
      certifications: newSupCerts.split(',').map((c) => c.trim()).filter(Boolean),
      specialty: newSupSpecialty || 'Fábrica y maquila personalizada agregada por el usuario.',
      whatsapp: newSupWhatsapp || '+573000000000',
      email: newSupEmail,
      website: newSupWebsite,
      image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=500&auto=format&fit=crop&q=80',
      isUserAdded: true
    };

    const updated = [createdSupplier, ...suppliers];
    setSuppliers(updated);
    setSelectedSupplier(createdSupplier);

    // Save only user added to localStorage
    const userAddedOnly = updated.filter((s) => s.isUserAdded);
    localStorage.setItem(STORAGE_KEY_CUSTOM_SUPPLIERS, JSON.stringify(userAddedOnly));

    setIsAddSupplierModalOpen(false);
    alert(`¡Proveedor "${createdSupplier.name}" (${createdSupplier.country} ${createdSupplier.flag}) registrado exitosamente!`);
  };

  // Submit Rating & Review handler
  const handleSubmitReview = (e: React.FormEvent) => {
    e.preventDefault();
    if (!reviewTitle.trim() || !reviewComment.trim()) {
      alert('Por favor escribe un título y tu opinión detallada.');
      return;
    }

    const overall = (rateQuality + rateDelivery + rateSupport + ratePrice) / 4;

    const newRev: SupplierReview = {
      id: 'rev-' + Date.now(),
      supplierId: activeSupplier.id,
      authorName: user?.name || 'Diseñador Aether',
      authorCompany: user?.company || 'Marca Verificada',
      ratingQuality: rateQuality,
      ratingDelivery: rateDelivery,
      ratingSupport: rateSupport,
      ratingPrice: ratePrice,
      overallRating: overall,
      title: reviewTitle.trim(),
      comment: reviewComment.trim(),
      isVerifiedBuyer: true,
      wouldRecommend: wouldRecommend,
      date: 'Hoy (' + new Date().toLocaleDateString() + ')'
    };

    const updatedReviews = [newRev, ...reviews];
    setReviews(updatedReviews);
    localStorage.setItem(STORAGE_KEY_REVIEWS, JSON.stringify(updatedReviews));

    // Update supplier composite rating
    const currentSupRevs = updatedReviews.filter((r) => r.supplierId === activeSupplier.id);
    const avgRating = currentSupRevs.reduce((acc, r) => acc + r.overallRating, 0) / currentSupRevs.length;

    setSuppliers((list) =>
      list.map((s) =>
        s.id === activeSupplier.id
          ? { ...s, rating: Number(avgRating.toFixed(1)), reviewsCount: currentSupRevs.length }
          : s
      )
    );

    setIsRateSupplierModalOpen(false);
    setReviewTitle('');
    setReviewComment('');
    alert('¡Tu calificación y reseña B2B ha sido publicada con sello de Comprador Verificado!');
  };

  const handleOpenTechPack = (sup?: Supplier) => {
    const target = sup || activeSupplier;
    setSelectedSupplier(target);
    setTechPackLang(target.defaultLang as any || 'en');
    setIsTechPackModalOpen(true);
  };

  const handleWhatsAppContact = () => {
    const text = encodeURIComponent(
      `Hola ${activeSupplier.name}, soy ${user?.name || 'Diseñador'} de la marca ${user?.company || 'Aether Studio'}. Estoy interesado en cotizar un lote de ${orderQuantity} unidades con ficha técnica Tech Pack.`
    );
    window.open(`https://wa.me/${activeSupplier.whatsapp.replace('+', '')}?text=${text}`, '_blank');
  };

  const tPack = TECHPACK_I18N[techPackLang] || TECHPACK_I18N.en;

  return (
    <div className="p-3 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-6 animate-fadeIn text-white font-mono text-xs select-none">
      {/* Executive Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-cyber-900/95 p-6 rounded-3xl border border-cyber-gold/50 shadow-cyber-card backdrop-blur-xl">
        <div className="flex items-center gap-3.5">
          <div className="p-3.5 rounded-2xl bg-cyber-gold/20 border border-cyber-gold text-cyber-gold shadow-gold-glow shrink-0">
            <Globe2 className="w-7 h-7" />
          </div>
          <div>
            <div className="flex items-center gap-2.5">
              <h2 className="text-xl sm:text-2xl font-tech font-extrabold text-white tracking-wider">
                DIRECTORIO B2B GLOBAL DE PROVEEDORES & SOURCING
              </h2>
              <span className="text-[10px] font-mono font-bold px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/50">
                RED AUDITADA & COMUNITARIA
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-1">
              Directorio internacional de fábricas de confección, calzado, muebles, cuero y troqueles. Agrega tus proveedores propios y califícalos con feedback verificado.
            </p>
          </div>
        </div>

        {/* Global Action Buttons */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => setIsAddSupplierModalOpen(true)}
            className="px-4 py-2.5 rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-600 hover:opacity-95 text-black font-tech font-extrabold text-xs uppercase tracking-wider shadow-md flex items-center gap-1.5 transition-all"
          >
            <Plus className="w-4 h-4" />
            <span>+ Agregar Proveedor B2B</span>
          </button>

          <button
            onClick={() => handleOpenTechPack()}
            className="px-4 py-2.5 rounded-2xl bg-gradient-to-r from-cyber-gold via-amber-400 to-yellow-500 text-black font-tech font-bold text-xs uppercase tracking-wider shadow-gold-glow hover:opacity-90 transition-all flex items-center gap-1.5"
          >
            <FileText className="w-4 h-4" />
            <span>Generar Tech Pack PDF</span>
          </button>
        </div>
      </div>

      {/* Filter & Sourcing Categories Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-cyber-900/90 p-4 rounded-3xl border border-cyber-800 shadow-cyber-card">
        <div className="flex flex-wrap items-center gap-2.5 w-full sm:w-auto">
          {/* Search Input */}
          <div className="relative flex-1 sm:w-64">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Buscar fábrica, ciudad o material..."
              className="w-full bg-cyber-950 border border-cyber-700 rounded-xl pl-9 pr-3 py-2 text-xs text-white focus:outline-none focus:border-cyber-gold"
            />
          </div>

          {/* Country Selector (Multi-Country Support) */}
          <select
            value={selectedCountry}
            onChange={(e) => setSelectedCountry(e.target.value)}
            className="bg-cyber-950 border border-cyber-700 text-white rounded-xl px-3 py-2 text-xs focus:outline-none focus:border-cyber-gold cursor-pointer"
          >
            <option value="all">🌍 Todos los Países</option>
            <option value="colombia">🇨🇴 Colombia</option>
            <option value="méxico">🇲🇽 México</option>
            <option value="portugal">🇵🇹 Portugal</option>
            <option value="turquía">🇹🇷 Turquía</option>
            <option value="italia">🇮🇹 Italia</option>
            <option value="españa">🇪🇸 España</option>
            <option value="china">🇨🇳 China</option>
            <option value="perú">🇵🇪 Perú</option>
            <option value="brasil">🇧🇷 Brasil</option>
            <option value="estados unidos">🇺🇸 Estados Unidos</option>
          </select>

          {/* Industry Category Filter */}
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="bg-cyber-950 border border-cyber-700 text-white rounded-xl px-3 py-2 text-xs focus:outline-none focus:border-cyber-gold cursor-pointer"
          >
            <option value="all">🏭 Todos los Sectores</option>
            <option value="fashion">👗 Moda & Confección</option>
            <option value="footwear">👟 Calzado & Sneakers</option>
            <option value="furniture">🪑 Muebles & Madera CNC</option>
            <option value="packaging">📦 Packaging & Troqueles</option>
            <option value="textile">🧵 Telas & Hilaturas</option>
          </select>

          {/* Certification Filter */}
          <select
            value={selectedCert}
            onChange={(e) => setSelectedCert(e.target.value)}
            className="bg-cyber-950 border border-cyber-700 text-white rounded-xl px-3 py-2 text-xs focus:outline-none focus:border-cyber-gold cursor-pointer hidden md:block"
          >
            <option value="all">🌿 Sellos & Auditorías</option>
            <option value="gots">GOTS Orgánico</option>
            <option value="oeko-tex">OEKO-TEX 100</option>
            <option value="fair trade">Fair Trade</option>
            <option value="b-corp">B-Corp</option>
            <option value="iso">ISO 9001</option>
          </select>
        </div>

        <div className="text-slate-400 text-[11px] font-mono">
          Mostrando <strong className="text-cyber-gold">{filteredSuppliers.length}</strong> fábricas verificadas
        </div>
      </div>

      {/* Main Grid: Suppliers List + Active Supplier Quoter */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left 7 Cols: Suppliers List */}
        <div className="lg:col-span-7 space-y-4">
          {filteredSuppliers.map((sup) => {
            const isSelected = activeSupplier.id === sup.id;
            const supReviews = reviews.filter((r) => r.supplierId === sup.id);

            return (
              <div
                key={sup.id}
                onClick={() => setSelectedSupplier(sup)}
                className={`p-5 rounded-3xl border transition-all cursor-pointer space-y-3.5 ${
                  isSelected
                    ? 'bg-cyber-900 border-cyber-gold shadow-gold-glow-lg'
                    : 'bg-cyber-950 border-cyber-800 hover:border-cyber-700 shadow-cyber-card'
                }`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-center gap-3.5">
                    <img
                      src={sup.image}
                      alt={sup.name}
                      className="w-14 h-14 rounded-2xl object-cover border border-cyber-gold/50 shadow-md shrink-0"
                    />
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-2xl">{sup.flag}</span>
                        <h3 className="font-tech font-bold text-base text-white">{sup.name}</h3>
                        {sup.isUserAdded && (
                          <span className="px-2 py-0.5 rounded text-[9px] font-bold bg-purple-500/20 text-purple-300 border border-purple-500/40">
                            PROVEEDOR PROPIO
                          </span>
                        )}
                      </div>
                      <div className="text-xs text-slate-400 flex items-center gap-2 mt-0.5">
                        <span className="flex items-center gap-1">
                          <MapPin className="w-3.5 h-3.5 text-cyber-gold" /> {sup.city}, {sup.country}
                        </span>
                        <span>•</span>
                        <span className="text-cyan-300 font-bold">{sup.categoryLabel}</span>
                      </div>
                    </div>
                  </div>

                  <div className="text-right shrink-0">
                    <div className="flex items-center justify-end gap-1 text-cyber-gold font-bold text-sm">
                      <Star className="w-4 h-4 fill-cyber-gold text-cyber-gold" />
                      <span>{sup.rating.toFixed(1)}</span>
                      <span className="text-[10px] text-slate-400 font-normal">({sup.reviewsCount || supReviews.length})</span>
                    </div>
                    <span className="text-base font-tech font-extrabold text-white block mt-0.5">
                      ${sup.pricePerUnit.toFixed(2)} USD
                    </span>
                    <span className="text-[10px] text-slate-500 font-mono">MOQ: {sup.moq} u.</span>
                  </div>
                </div>

                <p className="text-xs text-slate-300 leading-relaxed font-sans">{sup.specialty}</p>

                {/* Certifications & Lead Time */}
                <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t border-cyber-800 text-xs">
                  <div className="flex flex-wrap gap-1.5">
                    {sup.certifications.map((cert) => (
                      <span
                        key={cert}
                        className="px-2.5 py-0.5 rounded-lg bg-cyber-900 border border-cyber-700 text-emerald-400 text-[10px] font-mono flex items-center gap-1"
                      >
                        <ShieldCheck className="w-3 h-3" /> {cert}
                      </span>
                    ))}
                  </div>

                  <span className="text-slate-400 font-mono text-[11px] flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5 text-slate-500" /> Entrega: {sup.leadTime}
                  </span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Right 5 Cols: Active Factory Details, Quoter & Community Ratings */}
        <div className="lg:col-span-5 space-y-4">
          <div className="p-6 rounded-3xl bg-cyber-900 border-2 border-cyber-gold/60 shadow-gold-glow-lg space-y-5">
            {/* Active Header */}
            <div className="flex items-center justify-between pb-3 border-b border-cyber-800">
              <div>
                <span className="text-[10px] font-bold uppercase text-slate-400 block">Fábrica Seleccionada:</span>
                <h3 className="font-tech font-bold text-lg text-white">{activeSupplier.name}</h3>
                <span className="text-xs text-cyan-300">{activeSupplier.city}, {activeSupplier.country}</span>
              </div>
              <span className="text-3xl">{activeSupplier.flag}</span>
            </div>

            {/* Ratings & Reviews Breakdown Box */}
            <div className="p-4 rounded-2xl bg-cyber-950 border border-cyber-800 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="flex items-center text-cyber-gold">
                    {[1, 2, 3, 4, 5].map((st) => (
                      <Star
                        key={st}
                        className={`w-4 h-4 ${
                          st <= Math.round(activeSupplier.rating) ? 'fill-cyber-gold text-cyber-gold' : 'text-slate-600'
                        }`}
                      />
                    ))}
                  </div>
                  <span className="font-tech font-extrabold text-base text-white">{activeSupplier.rating.toFixed(1)}</span>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={() => setIsReviewsDrawerOpen(true)}
                    className="text-cyan-400 hover:underline text-[11px] font-bold"
                  >
                    Ver {activeSupplierReviews.length} Reseñas
                  </button>

                  <button
                    onClick={() => setIsRateSupplierModalOpen(true)}
                    className="px-2.5 py-1 rounded-lg bg-cyber-gold/20 text-cyber-gold border border-cyber-gold/40 text-[10px] font-bold hover:bg-cyber-gold hover:text-black transition-all"
                  >
                    ⭐ Calificar
                  </button>
                </div>
              </div>

              {/* 4 B2B Dimensions */}
              <div className="grid grid-cols-2 gap-2 text-[10px] text-slate-400 pt-1 border-t border-cyber-800/80">
                <div>✨ Calidad Material: <strong className="text-emerald-400">4.9 / 5.0</strong></div>
                <div>⏱️ Puntualidad: <strong className="text-cyan-300">4.8 / 5.0</strong></div>
                <div>💬 Soporte Técnico: <strong className="text-purple-300">5.0 / 5.0</strong></div>
                <div>💰 Relación Precio: <strong className="text-cyber-gold">4.9 / 5.0</strong></div>
              </div>
            </div>

            {/* Volume Quantity Slider */}
            <div>
              <div className="flex justify-between text-xs mb-1.5">
                <span className="text-slate-300 font-tech font-bold uppercase">Volumen de Producción:</span>
                <span className="font-tech font-extrabold text-cyber-gold text-sm">{orderQuantity} piezas</span>
              </div>
              <input
                type="range"
                min={activeSupplier.moq}
                max="3000"
                step="50"
                value={orderQuantity}
                onChange={(e) => setOrderQuantity(Number(e.target.value))}
                className="w-full accent-cyber-gold cursor-pointer"
              />
              <div className="flex justify-between text-[10px] font-mono text-slate-500 mt-1">
                <span>MOQ ({activeSupplier.moq} u.)</span>
                <span>1,000 u.</span>
                <span>2,000 u.</span>
                <span>3,000 u.</span>
              </div>
            </div>

            {/* Cost Breakdown Table */}
            <div className="p-4 rounded-2xl bg-cyber-950 border border-cyber-800 space-y-2 text-xs font-mono">
              <div className="flex justify-between text-slate-400">
                <span>Costo Confección ({orderQuantity} x ${activeSupplier.pricePerUnit}):</span>
                <span className="text-white font-bold">${totalProductionCost.toLocaleString()} USD</span>
              </div>
              <div className="flex justify-between text-slate-400">
                <span>Flete Aéreo Express DHL:</span>
                <span className="text-white">${estimatedShippingAir.toLocaleString()} USD</span>
              </div>
              <div className="flex justify-between text-slate-400">
                <span>Estimación Aranceles & Aduanas (8%):</span>
                <span className="text-white">${estimatedCustoms.toLocaleString()} USD</span>
              </div>

              <div className="pt-2 border-t border-cyber-800 flex justify-between items-center">
                <span className="font-tech font-bold text-white uppercase">Costo Total Puesto en Destino:</span>
                <span className="text-lg font-tech font-extrabold text-emerald-400">
                  ${grandTotalCost.toLocaleString()} USD
                </span>
              </div>

              <div className="text-right text-[11px] text-cyber-gold font-bold">
                Costo Unitario Final: ${costPerPieceLanded} USD / unidad
              </div>
            </div>

            {/* Action Buttons */}
            <div className="space-y-2 pt-1">
              <button
                onClick={handleWhatsAppContact}
                className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-emerald-500 via-teal-400 to-emerald-600 text-black font-tech font-extrabold text-xs uppercase tracking-wider shadow-md flex items-center justify-center gap-2 hover:opacity-95 transition-all"
              >
                <MessageCircle className="w-4 h-4" />
                <span>Contactar Fábrica por WhatsApp ({activeSupplier.whatsapp})</span>
              </button>

              <button
                onClick={() => handleOpenTechPack()}
                className="w-full py-2.5 rounded-xl bg-cyber-950 hover:bg-cyber-800 border border-cyber-700 text-cyber-gold font-tech font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition-all"
              >
                <FileText className="w-4 h-4" />
                <span>Ver Ficha Técnica TechPack Completa</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* =========================================================
          MODAL 1: AGREGAR NUEVO PROVEEDOR B2B (CUALQUIER PAÍS)
          ========================================================= */}
      {isAddSupplierModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
          <div className="bg-cyber-900 border border-emerald-500/50 rounded-3xl p-6 max-w-xl w-full shadow-cyber-card text-white space-y-4 max-h-[90vh] overflow-y-auto relative">
            <button
              onClick={() => setIsAddSupplierModalOpen(false)}
              className="absolute top-4 right-4 p-2 text-slate-400 hover:text-white"
            >
              <X className="w-4 h-4" />
            </button>

            <div className="flex items-center gap-3">
              <div className="p-3 rounded-2xl bg-emerald-500/20 text-emerald-400 border border-emerald-500">
                <Building className="w-6 h-6" />
              </div>
              <div>
                <h3 className="font-tech font-bold text-lg text-white">
                  REGISTRAR NUEVO PROVEEDOR / FÁBRICA B2B
                </h3>
                <p className="text-slate-400 text-xs">
                  Agrega una fábrica de cualquier país a tu red privada de abastecimiento
                </p>
              </div>
            </div>

            <form onSubmit={handleSaveNewSupplier} className="space-y-3 pt-2">
              <div>
                <label className="text-slate-300 font-bold block mb-1">Nombre de la Empresa / Fábrica:</label>
                <input
                  type="text"
                  required
                  value={newSupName}
                  onChange={(e) => setNewSupName(e.target.value)}
                  placeholder="ej: Manufacturas del Valle S.A.S."
                  className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-emerald-400"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-slate-300 font-bold block mb-1">País:</label>
                  <select
                    value={newSupCountry}
                    onChange={(e) => {
                      setNewSupCountry(e.target.value);
                      const flagsMap: Record<string, string> = {
                        'Colombia': '🇨🇴', 'México': '🇲🇽', 'Portugal': '🇵🇹', 'Turquía': '🇹🇷',
                        'Italia': '🇮🇹', 'España': '🇪🇸', 'China': '🇨🇳', 'Perú': '🇵🇪',
                        'Brasil': '🇧🇷', 'Estados Unidos': '🇺🇸', 'Vietnam': '🇻🇳', 'India': '🇮🇳'
                      };
                      setNewSupFlag(flagsMap[e.target.value] || '🌍');
                    }}
                    className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-emerald-400"
                  >
                    <option value="Colombia">🇨🇴 Colombia</option>
                    <option value="México">🇲🇽 México</option>
                    <option value="Portugal">🇵🇹 Portugal</option>
                    <option value="Turquía">🇹🇷 Turquía</option>
                    <option value="Italia">🇮🇹 Italia</option>
                    <option value="España">🇪🇸 España</option>
                    <option value="China">🇨🇳 China</option>
                    <option value="Perú">🇵🇪 Perú</option>
                    <option value="Brasil">🇧🇷 Brasil</option>
                    <option value="Estados Unidos">🇺🇸 Estados Unidos</option>
                    <option value="Vietnam">🇻🇳 Vietnam</option>
                    <option value="India">🇮🇳 India</option>
                  </select>
                </div>

                <div>
                  <label className="text-slate-300 font-bold block mb-1">Ciudad / Región:</label>
                  <input
                    type="text"
                    required
                    value={newSupCity}
                    onChange={(e) => setNewSupCity(e.target.value)}
                    placeholder="ej: Medellín, León, Oporto..."
                    className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-emerald-400"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-slate-300 font-bold block mb-1">Sector / Especialidad:</label>
                  <select
                    value={newSupCategory}
                    onChange={(e) => setNewSupCategory(e.target.value)}
                    className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-emerald-400"
                  >
                    <option value="fashion">👗 Moda & Confección</option>
                    <option value="footwear">👟 Calzado & Suelas</option>
                    <option value="furniture">🪑 Mobiliario & Madera CNC</option>
                    <option value="bags">👜 Cuero & Marroquinería</option>
                    <option value="packaging">📦 Packaging & Troqueles</option>
                    <option value="textile">🧵 Telas & Hilaturas</option>
                  </select>
                </div>

                <div>
                  <label className="text-slate-300 font-bold block mb-1">Precio Estimado Unitario ($ USD):</label>
                  <input
                    type="number"
                    step="0.1"
                    value={newSupPrice}
                    onChange={(e) => setNewSupPrice(Number(e.target.value))}
                    className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-emerald-400"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-slate-300 font-bold block mb-1">MOQ (Mínimo de Pedido):</label>
                  <input
                    type="number"
                    value={newSupMoq}
                    onChange={(e) => setNewSupMoq(Number(e.target.value))}
                    className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-emerald-400"
                  />
                </div>

                <div>
                  <label className="text-slate-300 font-bold block mb-1">WhatsApp de Contacto:</label>
                  <input
                    type="text"
                    required
                    value={newSupWhatsapp}
                    onChange={(e) => setNewSupWhatsapp(e.target.value)}
                    placeholder="ej: +573001234567"
                    className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-emerald-400"
                  />
                </div>
              </div>

              <div>
                <label className="text-slate-300 font-bold block mb-1">Certificaciones (separadas por coma):</label>
                <input
                  type="text"
                  value={newSupCerts}
                  onChange={(e) => setNewSupCerts(e.target.value)}
                  placeholder="GOTS Orgánico, OEKO-TEX 100, ISO 9001"
                  className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-emerald-400"
                />
              </div>

              <div>
                <label className="text-slate-300 font-bold block mb-1">Descripción de Capacidades Técnicas:</label>
                <textarea
                  value={newSupSpecialty}
                  onChange={(e) => setNewSupSpecialty(e.target.value)}
                  rows={2}
                  placeholder="Describe maquinaria, técnicas de costura, materiales que dominan..."
                  className="w-full bg-cyber-950 border border-cyber-700 rounded-xl p-3 text-xs text-white focus:outline-none focus:border-emerald-400 font-mono"
                />
              </div>

              <button
                type="submit"
                className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-emerald-500 via-teal-400 to-emerald-600 text-black font-tech font-extrabold text-xs uppercase tracking-wider shadow-md hover:opacity-95 transition-all"
              >
                💾 Guardar Proveedor en Catálogo
              </button>
            </form>
          </div>
        </div>
      )}

      {/* =========================================================
          MODAL 2: CALIFICAR Y RESEÑAR PROVEEDOR (4 DIMENSIONES B2B)
          ========================================================= */}
      {isRateSupplierModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
          <div className="bg-cyber-900 border border-cyber-gold/50 rounded-3xl p-6 max-w-lg w-full shadow-cyber-card text-white space-y-4 max-h-[90vh] overflow-y-auto relative">
            <button
              onClick={() => setIsRateSupplierModalOpen(false)}
              className="absolute top-4 right-4 p-2 text-slate-400 hover:text-white"
            >
              <X className="w-4 h-4" />
            </button>

            <div className="flex items-center gap-3">
              <div className="p-3 rounded-2xl bg-cyber-gold/20 text-cyber-gold border border-cyber-gold">
                <Star className="w-6 h-6 fill-cyber-gold" />
              </div>
              <div>
                <h3 className="font-tech font-bold text-lg text-white">
                  CALIFICAR PROVEEDOR B2B
                </h3>
                <p className="text-slate-400 text-xs">
                  Evaluando a: <strong>{activeSupplier.name} ({activeSupplier.flag} {activeSupplier.country})</strong>
                </p>
              </div>
            </div>

            <form onSubmit={handleSubmitReview} className="space-y-4 pt-2">
              {/* 4 Dimension Star Sliders */}
              <div className="space-y-3 p-4 rounded-2xl bg-cyber-950 border border-cyber-800">
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-300 font-bold">✨ Calidad de Materiales & Muestras:</span>
                  <div className="flex items-center gap-1 text-cyber-gold">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <button
                        type="button"
                        key={star}
                        onClick={() => setRateQuality(star)}
                        className="focus:outline-none"
                      >
                        <Star className={`w-4 h-4 ${star <= rateQuality ? 'fill-cyber-gold text-cyber-gold' : 'text-slate-700'}`} />
                      </button>
                    ))}
                  </div>
                </div>

                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-300 font-bold">⏱️ Puntualidad de Entrega (Lead Time):</span>
                  <div className="flex items-center gap-1 text-cyber-gold">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <button
                        type="button"
                        key={star}
                        onClick={() => setRateDelivery(star)}
                        className="focus:outline-none"
                      >
                        <Star className={`w-4 h-4 ${star <= rateDelivery ? 'fill-cyber-gold text-cyber-gold' : 'text-slate-700'}`} />
                      </button>
                    ))}
                  </div>
                </div>

                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-300 font-bold">💬 Soporte Técnico & Comunicación:</span>
                  <div className="flex items-center gap-1 text-cyber-gold">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <button
                        type="button"
                        key={star}
                        onClick={() => setRateSupport(star)}
                        className="focus:outline-none"
                      >
                        <Star className={`w-4 h-4 ${star <= rateSupport ? 'fill-cyber-gold text-cyber-gold' : 'text-slate-700'}`} />
                      </button>
                    ))}
                  </div>
                </div>

                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-300 font-bold">💰 Relación Calidad / Precio:</span>
                  <div className="flex items-center gap-1 text-cyber-gold">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <button
                        type="button"
                        key={star}
                        onClick={() => setRatePrice(star)}
                        className="focus:outline-none"
                      >
                        <Star className={`w-4 h-4 ${star <= ratePrice ? 'fill-cyber-gold text-cyber-gold' : 'text-slate-700'}`} />
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <div>
                <label className="text-slate-300 font-bold block mb-1">Título de la Reseña:</label>
                <input
                  type="text"
                  required
                  value={reviewTitle}
                  onChange={(e) => setReviewTitle(e.target.value)}
                  placeholder="ej: Confección impecable y entrega en tiempo récord"
                  className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-cyber-gold"
                />
              </div>

              <div>
                <label className="text-slate-300 font-bold block mb-1">Comentario & Experiencia de Producción:</label>
                <textarea
                  required
                  value={reviewComment}
                  onChange={(e) => setReviewComment(e.target.value)}
                  rows={3}
                  placeholder="Comparte detalles sobre telas, tolerancias de medida, empaque y trato del equipo..."
                  className="w-full bg-cyber-950 border border-cyber-700 rounded-xl p-3 text-xs text-white focus:outline-none focus:border-cyber-gold font-mono"
                />
              </div>

              <label className="flex items-center gap-2 cursor-pointer text-slate-300 text-xs">
                <input
                  type="checkbox"
                  checked={wouldRecommend}
                  onChange={(e) => setWouldRecommend(e.target.checked)}
                  className="rounded accent-emerald-400"
                />
                <span>Recomiendo esta fábrica para producción en serie</span>
              </label>

              <button
                type="submit"
                className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-cyber-gold via-amber-400 to-yellow-500 text-black font-tech font-extrabold text-xs uppercase tracking-wider shadow-gold-glow hover:opacity-95 transition-all"
              >
                ⭐ Publicar Calificación B2B
              </button>
            </form>
          </div>
        </div>
      )}

      {/* =========================================================
          MODAL 3: DRAWER DE RESEÑAS COMUNITARIAS
          ========================================================= */}
      {isReviewsDrawerOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
          <div className="bg-cyber-900 border border-cyber-800 rounded-3xl p-6 max-w-xl w-full shadow-2xl text-white space-y-4 max-h-[85vh] overflow-y-auto relative">
            <button
              onClick={() => setIsReviewsDrawerOpen(false)}
              className="absolute top-4 right-4 p-2 text-slate-400 hover:text-white"
            >
              <X className="w-4 h-4" />
            </button>

            <div className="flex items-center justify-between border-b border-cyber-800 pb-3">
              <div>
                <h3 className="font-tech font-bold text-lg text-white">
                  Reseñas Verificadas ({activeSupplierReviews.length})
                </h3>
                <span className="text-xs text-cyber-gold">{activeSupplier.name} ({activeSupplier.flag} {activeSupplier.country})</span>
              </div>
              <button
                onClick={() => {
                  setIsReviewsDrawerOpen(false);
                  setIsRateSupplierModalOpen(true);
                }}
                className="px-3 py-1.5 rounded-xl bg-cyber-gold text-black font-bold text-xs"
              >
                + Escribir Reseña
              </button>
            </div>

            <div className="space-y-3">
              {activeSupplierReviews.length === 0 ? (
                <div className="text-center py-8 text-slate-500">
                  Aún no hay reseñas para esta fábrica. ¡Sé el primero en calificarla!
                </div>
              ) : (
                activeSupplierReviews.map((rev) => (
                  <div key={rev.id} className="p-4 rounded-2xl bg-cyber-950 border border-cyber-800 space-y-2">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className="font-tech font-bold text-sm text-white">{rev.title}</span>
                        {rev.isVerifiedBuyer && (
                          <span className="px-1.5 py-0.5 rounded text-[9px] font-bold bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
                            COMPRADOR VERIFICADO
                          </span>
                        )}
                      </div>
                      <div className="flex items-center text-cyber-gold">
                        <Star className="w-3.5 h-3.5 fill-cyber-gold" />
                        <span className="text-xs font-bold ml-1">{rev.overallRating.toFixed(1)}</span>
                      </div>
                    </div>

                    <p className="text-xs text-slate-300 leading-relaxed">{rev.comment}</p>

                    <div className="flex items-center justify-between text-[10px] text-slate-500 pt-1 border-t border-cyber-900">
                      <span>Por <strong>{rev.authorName}</strong> ({rev.authorCompany})</span>
                      <span>{rev.date}</span>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      )}

      {/* =========================================================
          MODAL 4: TECH PACK VIEWER (PRESERVED)
          ========================================================= */}
      {isTechPackModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 bg-black/90 backdrop-blur-md animate-fadeIn">
          <div className="bg-white text-slate-900 rounded-3xl p-6 max-w-4xl w-full max-h-[95vh] overflow-y-auto space-y-6 shadow-2xl relative font-sans">
            <button
              onClick={() => setIsTechPackModalOpen(false)}
              className="absolute top-4 right-4 p-2 text-slate-500 hover:text-black rounded-full bg-slate-100"
            >
              <X className="w-5 h-5" />
            </button>

            {/* Tech Pack Header */}
            <div className="border-b-2 border-slate-900 pb-4 flex flex-wrap items-center justify-between gap-4">
              <div>
                <span className="text-[10px] font-mono font-bold tracking-widest text-slate-500 uppercase block">
                  {tPack.docRev}
                </span>
                <h2 className="text-xl sm:text-2xl font-black tracking-tight text-slate-950">
                  {tPack.docTitle}
                </h2>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => window.print()}
                  className="px-4 py-2 rounded-xl bg-slate-900 text-white text-xs font-bold flex items-center gap-1.5"
                >
                  <Printer className="w-4 h-4" />
                  <span>{tPack.printBtn}</span>
                </button>
              </div>
            </div>

            {/* Spec Sheet Meta */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 bg-slate-50 rounded-2xl border border-slate-200 text-xs">
              <div>
                <span className="text-slate-500 block font-bold">{tPack.styleLabel}</span>
                <span className="font-bold text-slate-900">Cyberwear Bomber X-1</span>
              </div>
              <div>
                <span className="text-slate-500 block font-bold">{tPack.factoryLabel}</span>
                <span className="font-bold text-slate-900">{activeSupplier.name} ({activeSupplier.country})</span>
              </div>
              <div>
                <span className="text-slate-500 block font-bold">{tPack.volumeLabel}</span>
                <span className="font-bold text-slate-900">{orderQuantity} Piezas</span>
              </div>
              <div>
                <span className="text-slate-500 block font-bold">{tPack.pantoneLabel}</span>
                <span className="font-mono text-slate-900 font-bold">19-4008 TCX / 14-0848</span>
              </div>
            </div>

            {/* BOM Table */}
            <div className="space-y-2">
              <h3 className="font-bold text-sm text-slate-950 uppercase">{tPack.bomTitle}</h3>
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-2 text-xs">
                <p><strong>{tPack.shellLabel}</strong> {tPack.shellDesc}</p>
                <p><strong>{tPack.zipperLabel}</strong> {tPack.zipperDesc}</p>
                <p><strong>{tPack.stitchLabel}</strong> {tPack.stitchDesc}</p>
              </div>
            </div>

            {/* Commercial Terms */}
            <div className="space-y-2">
              <h3 className="font-bold text-sm text-slate-950 uppercase">{tPack.commercialTitle}</h3>
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-2 text-xs">
                <p><strong>{tPack.incotermLabel}</strong> {tPack.incotermDesc}</p>
                <p><strong>{tPack.paymentLabel}</strong> {tPack.paymentDesc}</p>
                <p><strong>{tPack.ppsLabel}</strong> {tPack.ppsDesc}</p>
              </div>
            </div>

            {/* Signatures */}
            <div className="pt-4 border-t border-slate-300 grid grid-cols-2 gap-6 text-xs text-slate-700">
              <div className="space-y-8">
                <span>{tPack.brandSig}</span>
                <div className="border-b border-slate-400 pt-6">
                  <span className="text-[10px] text-slate-400">{tPack.signDate}</span>
                </div>
              </div>
              <div className="space-y-8">
                <span>{tPack.factorySig}</span>
                <div className="border-b border-slate-400 pt-6">
                  <span className="text-[10px] text-slate-400">{tPack.signDate}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
