import React, { useState } from 'react';
import {
  Globe2,
  MapPin,
  Clock,
  ShieldCheck,
  Phone,
  MessageCircle,
  FileText,
  DollarSign,
  Package,
  Layers,
  ChevronRight,
  Sparkles,
  Search,
  SlidersHorizontal,
  CheckCircle2,
  Download,
  Printer,
  X,
  Leaf,
  Ruler,
  Tag,
  Barcode,
  HelpCircle,
  PenTool,
  Check,
  Edit3,
  Save,
  Lock,
  Mail,
  Send,
  ShieldAlert,
  FileCode,
  Truck,
  Plane
} from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export interface Supplier {
  id: string;
  name: string;
  country: string;
  flag: string;
  city: string;
  defaultLang: 'pt' | 'tr' | 'es' | 'it' | 'en';
  moq: number;
  leadTime: string;
  pricePerUnit: number;
  rating: number;
  certifications: string[];
  specialty: string;
  whatsapp: string;
  image: string;
}

export type TechPackLanguage = 'en' | 'pt' | 'tr' | 'es' | 'it';

const TECHPACK_I18N: Record<TechPackLanguage, Record<string, string>> = {
  en: {
    docTitle: 'OFFICIAL PRODUCTION TECH PACK & SPECIFICATION',
    docRev: 'REV 3.4 • AUDITABLE FACTORY STANDARD',
    styleLabel: 'Style / Garment Name:',
    factoryLabel: 'Contracted Factory:',
    volumeLabel: 'PO Volume:',
    pantoneLabel: 'Pantone TCX Colors:',
    gradingTitle: '1. SIZING TABLE & GRADING SPECIFICATION',
    tolerance: 'Tolerance: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Point of Measure (POM)',
    baseSample: 'M (Base Sample)',
    chest: 'Chest Width (2.5cm below armhole)',
    length: 'Body Length (from High Point Shoulder)',
    sleeve: 'Raglan Sleeve Length (from Center Back)',
    hem: 'Bottom Hem Opening / Waist',
    commercialTitle: '2. COMMERCIAL TERMS, INCOTERMS & QUALITY PROTOCOL',
    incotermLabel: 'Commercial Incoterm 2020:',
    incotermDesc: 'FOB (Free On Board) Port of Origin or DDP (Delivered Duty Paid to client warehouse).',
    paymentLabel: 'Payment Milestones:',
    paymentDesc: '30% Deposit upon PO approval + 70% Balance against AQL 2.5 final inspection before dispatch.',
    ppsLabel: 'Pre-Production Sample (PPS):',
    ppsDesc: '1 Physical sample required within 7 business days for fit approval prior to bulk cutting.',
    bomTitle: '3. BILL OF MATERIALS (BOM) & STITCHING STANDARD',
    shellLabel: 'Shell Fabric:',
    shellDesc: '100% Nylon Ripstop 240 GSM with DWR water-repellent coating and matte anti-tear finish.',
    zipperLabel: 'Zippers & Trims:',
    zipperDesc: 'YKK Aquaguard #5 waterproof zippers with embossed matte silicone pullers.',
    stitchLabel: 'Stitch Density (SPI):',
    stitchDesc: 'Bonded poly 60/2 thread with 12 Stitches Per Inch (12 SPI) and Bar-Tack reinforcements.',
    careLabel: 'Care Instructions:',
    careDesc: 'Machine wash 30°C delicate, do not bleach, low iron max 110°C, do not dry clean.',
    signaturesTitle: '4. FORMAL APPROVAL SIGNATURES & LEGAL CONFORMITY',
    brandSig: 'Brand Creative Director Approval:',
    factorySig: 'Factory Production Plant Manager:',
    signDate: 'Signature & Date: ____________________',
    footerNotice: 'Official auditable document generated by Aether Synergy • Factory Legal Acceptance',
    printBtn: 'Print / Save Official PDF',
    editBtn: 'Edit Tech Pack',
    saveBtn: 'Save Changes'
  },
  pt: {
    docTitle: 'FICHA TÉCNICA OFICIAL DE PRODUÇÃO INDUSTRIAL',
    docRev: 'REV 3.4 • PADRÃO AUDITÁVEL DE CONFECÇÃO',
    styleLabel: 'Estilo / Nome da Peça:',
    factoryLabel: 'Fábrica Contratada:',
    volumeLabel: 'Volume da Ordem:',
    pantoneLabel: 'Cores Pantone TCX:',
    gradingTitle: '1. TABELA DE MEDIDAS E GRADUAÇÃO INDUSTRIAL',
    tolerance: 'Tolerância: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Ponto de Medição (POM)',
    baseSample: 'M (Amostra Base)',
    chest: 'Largura do Peito (2.5cm abaixo da cava)',
    length: 'Comprimento Total (do HPS ao fundo)',
    sleeve: 'Manga Raglan (do centro das costas)',
    hem: 'Abertura da Barra / Cintura',
    commercialTitle: '2. TERMOS COMERCIAIS, INCOTERMS E PROTOCOLO DE QUALIDADE',
    incotermLabel: 'Incoterm Comercial 2020:',
    incotermDesc: 'FOB (Free On Board) Porto de Origem ou DDP (Entrega no armazém do cliente com taxas pagas).',
    paymentLabel: 'Condições de Pagamento:',
    paymentDesc: '30% Sinal na aprovação da Ordem de Compra + 70% Saldo após inspeção final AQL 2.5.',
    ppsLabel: 'Amostra de Pré-Produção (PPS):',
    ppsDesc: '1 Amostra física (PPS) em 7 dias úteis para validação de modelagem antes do corte do tecido.',
    bomTitle: '3. LISTA DE MATERIAIS (BOM) E PADRÕES DE COSTURA',
    shellLabel: 'Tecido Exterior:',
    shellDesc: '100% Nylon Ripstop 240 GSM com acabamento DWR repelente a água e toque mate anti-rasgo.',
    zipperLabel: 'Fechos e Aviamentos:',
    zipperDesc: 'Fechos impermeáveis YKK Aquaguard #5 com puxadores em silicone personalizados.',
    stitchLabel: 'Densidade de Costura (SPI):',
    stitchDesc: 'Linha 60/2 com 12 pontos por polegada (12 SPI) e travetes de reforço Bar-Tack.',
    careLabel: 'Instruções de Lavagem:',
    careDesc: 'Lavar à máquina a 30°C ciclo suave, não usar lixívia, passar a ferro max 110°C.',
    signaturesTitle: '4. ASSINATURAS FORMAIS DE APROVAÇÃO E CONFORMIDADE',
    brandSig: 'Aprovação do Diretor Criativo da Marca:',
    factorySig: 'Aprovação do Gerente de Planta da Fábrica:',
    signDate: 'Assinatura e Data: ____________________',
    footerNotice: 'Documento oficial auditável gerado por Aether Synergy • Aceitação Legal de Fábrica',
    printBtn: 'Imprimir / Salvar PDF Oficial',
    editBtn: 'Editar Ficha Técnica',
    saveBtn: 'Salvar Alterações'
  },
  tr: {
    docTitle: 'RESMİ ÜRETİM VE KALIP TEKNİK ŞARTNAMESİ',
    docRev: 'REV 3.4 • DENETLENEBİLİR FABRİKA STANDARDI',
    styleLabel: 'Model / Ürün Adı:',
    factoryLabel: 'Anlaşmalı Fabrika:',
    volumeLabel: 'Sipariş Miktarı:',
    pantoneLabel: 'Pantone TCX Renkleri:',
    gradingTitle: '1. ÖLÇÜ TABLOSU VE BEDEN DERECELENDİRME',
    tolerance: 'Tolerans: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Ölçüm Noktası (POM)',
    baseSample: 'M (Numune Beden)',
    chest: 'Göğüs Genişliği (Koltuk altından 2.5cm)',
    length: 'Beden Boyu (Omuz yüksek noktasından)',
    sleeve: 'Reglan Kol Boyu (Arka ortadan)',
    hem: 'Etek Ucu / Bel Genişliği',
    commercialTitle: '2. TİCARİ ŞARTLAR, INCOTERMS VE KALİTE KONTROL',
    incotermLabel: 'Teslim Şekli (Incoterm 2020):',
    incotermDesc: 'FOB (Free On Board) Çıkış Limanı veya DDP (Gümrük vergileri ödenmiş teslimat).',
    paymentLabel: 'Ödeme Koşulları:',
    paymentDesc: '%30 Sipariş onayı ile Peşinat + %70 AQL 2.5 son kalite kontrolü sonrası sevk öncesi.',
    ppsLabel: 'İmalat Öncesi Numune (PPS):',
    ppsDesc: 'Kumaş kesiminden önce kalıp onayı için 7 iş günü içinde 1 adet onay numunesi.',
    bomTitle: '3. MALZEME LİSTESİ (BOM) VE DİKİŞ STANDARDI',
    shellLabel: 'Dış Kumaş:',
    shellDesc: '%100 Naylon Ripstop 240 GSM, DWR su itici kaplamalı ve mat yırtılmaz dokuma.',
    zipperLabel: 'Fermuar ve Aksesuarlar:',
    zipperDesc: 'YKK Aquaguard #5 su geçirmez fermuarlar ve özel silikon elcikler.',
    stitchLabel: 'Dikiş Sıklığı (SPI):',
    stitchDesc: 'İnç başına 12 dikiş (12 SPI) ve kritik noktalarda Bar-Tack punteriz takviyesi.',
    careLabel: 'Yıkama Talimatları:',
    careDesc: '30°C hassas makine yıkama, ağartıcı kullanılmaz, düşük ısıda maks 110°C ütüleme.',
    signaturesTitle: '4. RESMİ ONAY İMZALARI VE TEKNİK UYGUNLUK',
    brandSig: 'Marka Kreatif Direktörü Onayı:',
    factorySig: 'Fabrika Üretim ve Kalite Müdürü:',
    signDate: 'İmza ve Tarih: ____________________',
    footerNotice: 'Aether Synergy tarafından oluşturulan resmi teknik şartname belgesi',
    printBtn: 'Yazdır / PDF Olarak Kaydet',
    editBtn: 'Şartnameyi Düzenle',
    saveBtn: 'Değişiklikleri Kaydet'
  },
  it: {
    docTitle: 'SCHEDA TECNICA DI PRODUZIONE INDUSTRIALE',
    docRev: 'REV 3.4 • STANDARD AUDITABILE PER LA MANIFATTURA',
    styleLabel: 'Stile / Nome Capo:',
    factoryLabel: 'Fabbrica Assegnata:',
    volumeLabel: 'Volume Ordine:',
    pantoneLabel: 'Colori Pantone TCX:',
    gradingTitle: '1. TABELLA MISURE E GRADAZIONE INDUSTRIALE',
    tolerance: 'Tolleranza: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Punto di Misura (POM)',
    baseSample: 'M (Campione Base)',
    chest: 'Larghezza Torace (2.5cm sotto giromanica)',
    length: 'Lunghezza Totale (da punto spalla HPS)',
    sleeve: 'Manica Raglan (da centro schiena)',
    hem: 'Fondo / Larghezza Bacino',
    commercialTitle: '2. TERMINI COMMERCIALI, INCOTERMS E QUALITÀ',
    incotermLabel: 'Incoterm Commerciale 2020:',
    incotermDesc: 'FOB (Free On Board) Porto di Partenza o DDP (Reso Sdoganato a destinazione).',
    paymentLabel: 'Termini di Pagamento:',
    paymentDesc: '30% Anticipo all\'ordine + 70% Saldo previa ispezione finale di qualità AQL 2.5.',
    ppsLabel: 'Campione Pre-Produzione (PPS):',
    ppsDesc: '1 Prototipo fisico richiesto entro 7 giorni lavorativi per approvazione fitting prima del taglio.',
    bomTitle: '3. DISTINTA BASE (BOM) E STANDARD DI CUCITURA',
    shellLabel: 'Tessuto Esterno:',
    shellDesc: '100% Nylon Ripstop 240 GSM con finitura idrorepellente DWR e mano opaca antistrappo.',
    zipperLabel: 'Zip e Accessori:',
    zipperDesc: 'Zip termonastrate YKK Aquaguard #5 impermeabili con tiretti in silicone personalizzati.',
    stitchLabel: 'Densità di Cucitura (SPI):',
    stitchDesc: 'Filato 60/2 con 12 punti per pollice (12 SPI) e travette di rinforzo Bar-Tack.',
    careLabel: 'Istruzioni di Lavaggio:',
    careDesc: 'Lavaggio in lavatrice 30°C ciclo delicato, non candeggiare, stiro max 110°C.',
    signaturesTitle: '4. FIRME UFFICIALI DI APPROVAZIONE E CONFORMITÀ',
    brandSig: 'Approvazione Direttore Creativo Brand:',
    factorySig: 'Approvazione Direttore di Produzione Fabbrica:',
    signDate: 'Firma e Data: ____________________',
    footerNotice: 'Documento ufficiale generato da Aether Synergy • Accettazione Legale Manifattura',
    printBtn: 'Stampa / Salva PDF Ufficiale',
    editBtn: 'Modifica Scheda Tecnica',
    saveBtn: 'Salva Modifiche'
  },
  es: {
    docTitle: 'FICHA TÉCNICA OFICIAL DE PRODUCCIÓN INDUSTRIAL',
    docRev: 'REV 3.4 • ESTÁNDAR AUDITABLE DE CONFECCIÓN',
    styleLabel: 'Estilo / Prenda:',
    factoryLabel: 'Fábrica Asignada:',
    volumeLabel: 'Volumen de Orden:',
    pantoneLabel: 'Colores Pantone TCX:',
    gradingTitle: '1. TABLA DE MEDIDAS & GRADACIÓN INDUSTRIAL',
    tolerance: 'Tolerancia: +/- 0.5 cm (0.2 in)',
    pomHeader: 'Punto de Medida (POM)',
    baseSample: 'M (Muestra Base)',
    chest: 'Ancho de Pecho (2.5cm bajo sisa)',
    length: 'Largo Total (desde HPS)',
    sleeve: 'Largo de Manga Raglán (desde centro espalda)',
    hem: 'Ancho de Ruedo / Cintura',
    commercialTitle: '2. TÉRMINOS COMERCIALES, INCOTERMS & PROTOCOLO DE CALIDAD',
    incotermLabel: 'Término Comercial (Incoterm 2020):',
    incotermDesc: 'FOB (Free On Board) Puerto de Origen o DDP (Entregado en almacén destino con aranceles pagados).',
    paymentLabel: 'Condiciones de Pago:',
    paymentDesc: '30% Anticipo al aprobar Orden de Compra + 70% Saldo contra inspección final AQL 2.5 previa al despacho.',
    ppsLabel: 'Muestra Pre-Producción (PPS):',
    ppsDesc: '1 Prototipo físico (PPS) debe enviarse en 7 días hábiles para aprobación de calce antes del corte en serie.',
    bomTitle: '3. LISTA DE MATERIALES (BOM) & NORMAS DE COSTURA',
    shellLabel: 'Tejido Exterior:',
    shellDesc: '100% Nylon Ripstop 240 GSM con recubrimiento DWR repelente al agua y acabado mate anti-desgarro.',
    zipperLabel: 'Cremalleras & Herrajes:',
    zipperDesc: 'YKK Aquaguard #5 impermeables con tiradores de silicona negra grabados con logo Aether.',
    stitchLabel: 'Densidad de Costura (SPI):',
    stitchDesc: 'Hilo bondeado 60/2 con 12 puntadas por pulgada (12 SPI) y remates Bar-Tack en zonas de carga.',
    careLabel: 'Instrucciones de Lavado:',
    careDesc: 'Lavado a máquina 30°C ciclo suave, no usar cloro, planchar a temperatura baja (máx 110°C).',
    signaturesTitle: '4. FIRMAS DE APROBACIÓN Y CONFORMIDAD TÉCNICA',
    brandSig: 'Director Creativo / Marca:',
    factorySig: 'Gerente de Planta / Fábrica:',
    signDate: 'Firma & Fecha: ____________________',
    footerNotice: 'Documento oficial generado por Aether Synergy • Válido para producción internacional',
    printBtn: 'Imprimir / Guardar PDF Oficial',
    editBtn: 'Editar Ficha Técnica',
    saveBtn: 'Guardar Cambios'
  }
};

export const GlobalSuppliers: React.FC = () => {
  const { user } = useAuth();
  const [selectedSupplier, setSelectedSupplier] = useState<Supplier | null>(null);
  const [orderQuantity, setOrderQuantity] = useState<number>(250);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCountry, setSelectedCountry] = useState('all');
  const [selectedCert, setSelectedCert] = useState('all');
  const [isTechPackModalOpen, setIsTechPackModalOpen] = useState(false);
  const [isRFQModalOpen, setIsRFQModalOpen] = useState(false);
  const [isEscrowModalOpen, setIsEscrowModalOpen] = useState(false);
  const [isGCodeModalOpen, setIsGCodeModalOpen] = useState(false);
  const [isFreightModalOpen, setIsFreightModalOpen] = useState(false);
  const [isDPPModalOpen, setIsDPPModalOpen] = useState(false);
  const [destinationCountry, setDestinationCountry] = useState('Estados Unidos (US)');
  const [shippingMethod, setShippingMethod] = useState<'air' | 'sea'>('air');
  const [unitSystem, setUnitSystem] = useState<'both' | 'cm' | 'in'>('both');
  const [techPackLang, setTechPackLang] = useState<TechPackLanguage>('en');

  // Editable Tech Pack State
  const [isEditing, setIsEditing] = useState(false);
  const [customStyleName, setCustomStyleName] = useState('Chaqueta Techwear Modular X-1');
  const [customSKU, setCustomSKU] = useState('AET-JKT-2026-X49');
  const [customNotes, setCustomNotes] = useState('');

  const suppliers: Supplier[] = [
    {
      id: 'pt-porto-textiles',
      name: 'Porto Luxury Garments S.A.',
      country: 'Portugal',
      flag: '🇵🇹',
      city: 'Oporto',
      defaultLang: 'pt',
      moq: 100,
      leadTime: '18 - 24 días',
      pricePerUnit: 24.50,
      rating: 4.9,
      certifications: ['GOTS Orgánico', 'OEKO-TEX 100', 'ISO 9001'],
      specialty: 'Algodón francés pesado 460 GSM y confección techwear premium.',
      whatsapp: '+351912345678',
      image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=500&auto=format&fit=crop&q=80'
    },
    {
      id: 'tr-istanbul-craft',
      name: 'Bosphorus Apparel & Denim Ltd.',
      country: 'Turquía',
      flag: '🇹🇷',
      city: 'Estambul',
      defaultLang: 'tr',
      moq: 150,
      leadTime: '15 - 20 días',
      pricePerUnit: 18.20,
      rating: 4.8,
      certifications: ['OEKO-TEX 100', 'BSCI Audited'],
      specialty: 'Tejido técnico repelente al agua, lavados vintage y cremalleras selladas.',
      whatsapp: '+905321234567',
      image: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=500&auto=format&fit=crop&q=80'
    },
    {
      id: 'co-medellin-textiles',
      name: 'Andes Fabric & Tech S.A.S.',
      country: 'Colombia',
      flag: '🇨🇴',
      city: 'Medellín',
      defaultLang: 'es',
      moq: 80,
      leadTime: '12 - 16 días',
      pricePerUnit: 14.80,
      rating: 4.9,
      certifications: ['Fair Trade', 'GOTS Orgánico', 'Carbon Neutral'],
      specialty: 'Ropa urbana oversized, bordados de alta densidad y confección ágil.',
      whatsapp: '+573001234567',
      image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=500&auto=format&fit=crop&q=80'
    },
    {
      id: 'it-milan-atelier',
      name: 'Atelier Sartoriale Milano',
      country: 'Italia',
      flag: '🇮🇹',
      city: 'Milán',
      defaultLang: 'it',
      moq: 50,
      leadTime: '25 - 30 días',
      pricePerUnit: 48.00,
      rating: 5.0,
      certifications: ['Made in Italy Certified', 'B-Corp', 'OEKO-TEX 100'],
      specialty: 'Sastrería contemporánea, cueros de curtiduría toscana y piezas de pasarela.',
      whatsapp: '+390212345678',
      image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=500&auto=format&fit=crop&q=80'
    }
  ];

  const filteredSuppliers = suppliers.filter((s) => {
    const matchSearch =
      s.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      s.specialty.toLowerCase().includes(searchQuery.toLowerCase()) ||
      s.city.toLowerCase().includes(searchQuery.toLowerCase());
    const matchCountry = selectedCountry === 'all' || s.country.toLowerCase() === selectedCountry.toLowerCase();
    const matchCert = selectedCert === 'all' || s.certifications.some((c) => c.toLowerCase().includes(selectedCert.toLowerCase()));
    return matchSearch && matchCountry && matchCert;
  });

  const activeSupplier = selectedSupplier || suppliers[0];

  const handleOpenTechPack = (sup?: Supplier) => {
    const target = sup || activeSupplier;
    setSelectedSupplier(target);
    setTechPackLang(target.defaultLang || 'en');
    setIsTechPackModalOpen(true);
  };

  const totalProductionCost = activeSupplier.pricePerUnit * orderQuantity;
  const estimatedShippingAir = Math.round(orderQuantity * 3.2);
  const estimatedCustoms = Math.round(totalProductionCost * 0.08);
  const grandTotalCost = totalProductionCost + estimatedShippingAir + estimatedCustoms;
  const costPerPieceLanded = (grandTotalCost / orderQuantity).toFixed(2);

  const handleWhatsAppContact = () => {
    const text = encodeURIComponent(
      `Hola ${activeSupplier.name}, soy ${user?.name || 'Diseñador'} de la marca ${user?.company || 'Aether Studio'}. Estoy interesado en cotizar un lote de ${orderQuantity} unidades con ficha técnica Tech Pack.`
    );
    window.open(`https://wa.me/${activeSupplier.whatsapp.replace('+', '')}?text=${text}`, '_blank');
  };

  const tPack = TECHPACK_I18N[techPackLang] || TECHPACK_I18N.en;

  return (
    <div className="p-3 sm:p-6 lg:p-8 max-w-7xl mx-auto space-y-6 animate-fadeIn transition-colors">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-cyber-900/90 p-4 sm:p-6 rounded-3xl border border-cyber-gold/40 shadow-cyber-card">
        <div className="flex items-center gap-3.5">
          <div className="p-3 rounded-2xl bg-cyber-gold/20 border border-cyber-gold text-cyber-gold shadow-gold-glow shrink-0">
            <Globe2 className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2.5">
              <h2 className="text-xl sm:text-2xl font-tech font-extrabold text-white tracking-wider">
                GLOBAL SUPPLIERS B2B & TECH PACK SUITE
              </h2>
              <span className="text-[10px] font-mono font-bold px-2.5 py-0.5 rounded-full bg-cyber-800 text-cyber-gold border border-cyber-700 hidden sm:inline">
                RED AUDITADA 2026
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Directorio verificado de fábricas en Europa y América con cotizaciones de volumen y fichas técnicas
            </p>
          </div>
        </div>

        <button
          onClick={() => handleOpenTechPack()}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-5 py-2.5 rounded-2xl bg-gradient-to-r from-cyber-gold via-amber-400 to-yellow-500 text-black font-tech font-bold text-xs uppercase tracking-wider shadow-gold-glow hover:opacity-90 transition-all"
        >
          <FileText className="w-4 h-4" />
          <span>Generar Tech Pack PDF Multilingüe</span>
        </button>
      </div>

      {/* Filter & Search Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-cyber-900/60 p-3 rounded-2xl border border-cyber-800">
        <div className="flex flex-wrap items-center gap-2.5 w-full sm:w-auto">
          <div className="relative flex-1 sm:flex-none">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Buscar fábrica o tejido..."
              className="w-full bg-cyber-950 border border-cyber-700 rounded-xl pl-9 pr-3 py-1.5 text-xs text-white focus:outline-none focus:border-cyber-gold"
            />
          </div>

          <select
            value={selectedCountry}
            onChange={(e) => setSelectedCountry(e.target.value)}
            className="bg-cyber-950 border border-cyber-700 text-white rounded-xl px-3 py-1.5 text-xs focus:outline-none focus:border-cyber-gold cursor-pointer"
          >
            <option value="all">🌍 Todos los Países</option>
            <option value="portugal">🇵🇹 Portugal</option>
            <option value="turquía">🇹🇷 Turquía</option>
            <option value="colombia">🇨🇴 Colombia</option>
            <option value="italia">🇮🇹 Italia</option>
          </select>

          <select
            value={selectedCert}
            onChange={(e) => setSelectedCert(e.target.value)}
            className="bg-cyber-950 border border-cyber-700 text-white rounded-xl px-3 py-1.5 text-xs focus:outline-none focus:border-cyber-gold cursor-pointer"
          >
            <option value="all">🌿 Todos los Sellos</option>
            <option value="gots">GOTS Orgánico</option>
            <option value="oeko-tex">OEKO-TEX 100</option>
            <option value="fair trade">Fair Trade</option>
            <option value="b-corp">B-Corp</option>
          </select>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left 7 Cols: Suppliers Cards */}
        <div className="lg:col-span-7 space-y-4">
          {filteredSuppliers.map((sup) => {
            const isSelected = activeSupplier.id === sup.id;

            return (
              <div
                key={sup.id}
                onClick={() => setSelectedSupplier(sup)}
                className={`p-4 sm:p-5 rounded-3xl border transition-all cursor-pointer space-y-3 ${
                  isSelected
                    ? 'bg-cyber-900 border-cyber-gold shadow-gold-glow-lg'
                    : 'bg-cyber-950/80 border-cyber-800 hover:border-cyber-gold/50 shadow-cyber-card'
                }`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-center gap-3">
                    <img
                      src={sup.image}
                      alt={sup.name}
                      className="w-12 h-12 sm:w-14 sm:h-14 rounded-2xl object-cover border border-cyber-gold/50 shadow-md shrink-0"
                    />
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-xl">{sup.flag}</span>
                        <h3 className="font-tech font-bold text-sm sm:text-base text-white">{sup.name}</h3>
                      </div>
                      <div className="text-xs text-slate-400 flex items-center gap-1 mt-0.5">
                        <MapPin className="w-3.5 h-3.5 text-cyber-gold" /> {sup.city}, {sup.country}
                      </div>
                    </div>
                  </div>

                  <div className="text-right shrink-0">
                    <span className="text-xs text-slate-400 block">Desde</span>
                    <span className="text-base sm:text-lg font-tech font-extrabold text-cyber-gold">${sup.pricePerUnit.toFixed(2)} USD</span>
                    <span className="text-[10px] text-slate-400 block font-mono">MOQ: {sup.moq} u.</span>
                  </div>
                </div>

                <p className="text-xs text-slate-300 font-sans leading-relaxed">{sup.specialty}</p>

                <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t border-cyber-855 text-xs">
                  <div className="flex flex-wrap gap-1.5">
                    {sup.certifications.map((cert) => (
                      <span
                        key={cert}
                        className="px-2 py-0.5 rounded-md bg-cyber-900 border border-cyber-750 text-emerald-400 text-[10px] font-mono flex items-center gap-1"
                      >
                        <ShieldCheck className="w-3 h-3" /> {cert}
                      </span>
                    ))}
                  </div>

                  <span className="text-slate-400 font-mono text-[11px] flex items-center gap-1">
                    <Clock className="w-3 h-3 text-slate-500" /> Lead Time: {sup.leadTime}
                  </span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Right 5 Cols: Dynamic Sourcing Quote Panel */}
        <div className="lg:col-span-5 space-y-4">
          <div className="p-4 sm:p-6 rounded-3xl bg-cyber-900 border-2 border-cyber-gold/50 shadow-gold-glow-lg space-y-5">
            <div className="flex items-center justify-between pb-3 border-b border-cyber-800">
              <div>
                <span className="text-[10px] font-bold uppercase text-slate-400 block">Fábrica Seleccionada:</span>
                <h3 className="font-tech font-bold text-sm sm:text-base text-white">{activeSupplier.name}</h3>
              </div>
              <span className="text-2xl">{activeSupplier.flag}</span>
            </div>

            {/* Volume Quantity Slider */}
            <div>
              <div className="flex justify-between text-xs mb-1.5">
                <span className="text-slate-300 font-tech font-bold uppercase">Volumen de Producción:</span>
                <span className="font-tech font-extrabold text-cyber-gold text-sm">{orderQuantity} piezas</span>
              </div>
              <input
                type="range"
                min={activeSupplier.moq}
                max="2500"
                step="50"
                value={orderQuantity}
                onChange={(e) => setOrderQuantity(Number(e.target.value))}
                className="w-full accent-cyber-gold cursor-pointer"
              />
              <div className="flex justify-between text-[10px] font-mono text-slate-500 mt-1">
                <span>MOQ ({activeSupplier.moq} u.)</span>
                <span>500 u.</span>
                <span>1,000 u.</span>
                <span>2,500 u.</span>
              </div>
            </div>

            {/* Cost Breakdown Table */}
            <div className="p-4 rounded-2xl bg-cyber-950 border border-cyber-800 space-y-2 text-xs">
              <div className="flex justify-between text-slate-400">
                <span>Costo Confección ({orderQuantity} x ${activeSupplier.pricePerUnit}):</span>
                <span className="font-mono text-white">${totalProductionCost.toLocaleString()} USD</span>
              </div>
              <div className="flex justify-between text-slate-400">
                <span>Flete Aéreo Express DHL:</span>
                <span className="font-mono text-white">${estimatedShippingAir.toLocaleString()} USD</span>
              </div>
              <div className="flex justify-between text-slate-400">
                <span>Estimación Aranceles & Aduanas (8%):</span>
                <span className="font-mono text-white">${estimatedCustoms.toLocaleString()} USD</span>
              </div>

              <div className="pt-2 border-t border-cyber-800 flex justify-between items-center">
                <span className="font-tech font-bold text-white uppercase">Costo Total Puesto en Destino:</span>
                <span className="text-base sm:text-lg font-tech font-extrabold text-emerald-400">
                  ${grandTotalCost.toLocaleString()} USD
                </span>
              </div>

              <div className="text-right text-[11px] font-mono text-cyber-gold">
                Costo Unitario Final: ${costPerPieceLanded} USD / prenda
              </div>
            </div>

            {/* Action Buttons */}
            <div className="space-y-2">
              <button
                onClick={() => setIsRFQModalOpen(true)}
                className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-cyber-gold via-amber-400 to-yellow-500 text-black font-tech font-bold text-sm uppercase tracking-wider shadow-gold-glow flex items-center justify-center gap-2 hover:opacity-90 transition-all"
              >
                <Send className="w-4 h-4" />
                <span>⚡ Enviar Solicitud RFQ (WhatsApp / Email)</span>
              </button>

              <button
                onClick={() => setIsFreightModalOpen(true)}
                className="w-full py-2.5 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 border border-amber-500/50 text-amber-300 font-tech font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition-colors"
              >
                <Truck className="w-4 h-4" />
                <span>🚚 Cotizador de Envíos Internacionales & Aduanas (DHL)</span>
              </button>

              <div className="grid grid-cols-2 gap-2">
                <button
                  onClick={() => setIsEscrowModalOpen(true)}
                  className="py-2.5 rounded-xl bg-purple-500/20 hover:bg-purple-500/30 border border-purple-500/50 text-purple-300 font-tech font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition-colors"
                >
                  <Lock className="w-3.5 h-3.5" />
                  <span>Contrato Escrow</span>
                </button>

                <button
                  onClick={() => setIsGCodeModalOpen(true)}
                  className="py-2.5 rounded-xl bg-cyan-500/20 hover:bg-cyan-500/30 border border-cyan-500/50 text-cyan-300 font-tech font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition-colors"
                >
                  <FileCode className="w-3.5 h-3.5" />
                  <span>Exportar G-Code 3D</span>
                </button>
              </div>

              <button
                onClick={() => setIsDPPModalOpen(true)}
                className="w-full py-2.5 rounded-xl bg-emerald-500/20 hover:bg-emerald-500/30 border border-emerald-500/50 text-emerald-300 font-tech font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-1.5 transition-colors"
              >
                <Tag className="w-4 h-4" />
                <span>🏷️ Pasaporte Digital de Producto (EU DPP 2026 & QR)</span>
              </button>

              <button
                onClick={() => handleOpenTechPack()}
                className="w-full py-3 rounded-2xl bg-cyber-950 hover:bg-cyber-850 border border-cyber-700 text-white font-tech font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-2 transition-colors"
              >
                <FileText className="w-4 h-4 text-cyber-gold" />
                <span>Ver Ficha Técnica Tech Pack Multilingüe</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* ⚡ 1. MODAL RFQ INSTANTÁNEO */}
      {isRFQModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
          <div className="relative w-full max-w-lg bg-cyber-900 border border-cyber-gold/50 rounded-3xl p-6 shadow-gold-glow-lg text-white space-y-4">
            <button
              onClick={() => setIsRFQModalOpen(false)}
              className="absolute top-5 right-5 p-2 text-slate-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-cyber-gold/20 text-cyber-gold border border-cyber-gold">
                <Send className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-tech font-bold text-lg">DESPACHAR SOLICITUD DE COTIZACIÓN (RFQ)</h3>
                <p className="text-xs text-slate-400">Fábrica: {activeSupplier.name} ({activeSupplier.country})</p>
              </div>
            </div>

            <div className="p-3.5 rounded-2xl bg-cyber-950 border border-cyber-800 text-xs space-y-2 font-mono text-slate-300">
              <div className="flex justify-between">
                <span className="text-slate-400">Estilo / SKU:</span>
                <span className="text-white font-bold">{customSKU}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Volumen del Lote:</span>
                <span className="text-cyber-gold font-bold">{orderQuantity} unidades</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Tiempo Solicitado:</span>
                <span className="text-emerald-400 font-bold">{activeSupplier.leadTime}</span>
              </div>
              <div className="pt-2 border-t border-cyber-800 text-[11px] text-slate-400">
                Se adjunta enlace seguro con token de acceso a la Ficha Técnica Tech Pack y archivos 3D .GLB.
              </div>
            </div>

            <div className="flex gap-3 pt-2">
              <button
                onClick={handleWhatsAppContact}
                className="flex-1 py-3 rounded-2xl bg-emerald-500 hover:bg-emerald-400 text-black font-tech font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-2 shadow-md transition-all"
              >
                <MessageCircle className="w-4 h-4 fill-current" />
                <span>Despachar por WhatsApp</span>
              </button>

              <button
                onClick={() => {
                  window.location.href = `mailto:sales@${activeSupplier.id}.com?subject=Solicitud RFQ Lote ${orderQuantity}u - ${customSKU}&body=Estimado equipo de ${activeSupplier.name}, adjuntamos solicitud formal de cotización y ficha técnica generada en Aether Synergy.`;
                }}
                className="flex-1 py-3 rounded-2xl bg-cyber-800 hover:bg-cyber-700 text-white font-tech font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-2 transition-all border border-cyber-700"
              >
                <Mail className="w-4 h-4" />
                <span>Enviar por Correo</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 🔒 2. MODAL CONTRATO ESCROW / FIDEICOMISO */}
      {isEscrowModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
          <div className="relative w-full max-w-lg bg-cyber-900 border border-purple-500/50 rounded-3xl p-6 shadow-cyber-card text-white space-y-4">
            <button
              onClick={() => setIsEscrowModalOpen(false)}
              className="absolute top-5 right-5 p-2 text-slate-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-purple-500/20 text-purple-300 border border-purple-500">
                <Lock className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-tech font-bold text-lg">CONTRATO DE PAGO EN ESCROW (FIDEICOMISO)</h3>
                <p className="text-xs text-slate-400">Protección de Fondos contra Fraude & Calidad</p>
              </div>
            </div>

            <div className="space-y-2 text-xs">
              <div className="p-3 rounded-xl bg-cyber-950 border border-cyber-800 flex justify-between items-center">
                <div>
                  <span className="font-bold text-white block">Hito 1: Depósito de Inicio (30%)</span>
                  <span className="text-[10px] text-slate-400">Liberado al iniciar compra de tela</span>
                </div>
                <span className="font-mono font-bold text-purple-300">${(grandTotalCost * 0.3).toFixed(2)} USD</span>
              </div>

              <div className="p-3 rounded-xl bg-cyber-950 border border-cyber-800 flex justify-between items-center">
                <div>
                  <span className="font-bold text-white block">Hito 2: Muestra PPS Aprobada (40%)</span>
                  <span className="text-[10px] text-slate-400">Liberado al aprobar muestra física</span>
                </div>
                <span className="font-mono font-bold text-purple-300">${(grandTotalCost * 0.4).toFixed(2)} USD</span>
              </div>

              <div className="p-3 rounded-xl bg-cyber-950 border border-cyber-800 flex justify-between items-center">
                <div>
                  <span className="font-bold text-white block">Hito 3: Inspección Final AQL 2.5 (30%)</span>
                  <span className="text-[10px] text-slate-400">Liberado antes de despacho aduanero</span>
                </div>
                <span className="font-mono font-bold text-emerald-400">${(grandTotalCost * 0.3).toFixed(2)} USD</span>
              </div>
            </div>

            <button
              onClick={() => {
                alert('¡Contrato Escrow activado en custodia bancaria! Los fondos permanecerán retenidos de forma segura.');
                setIsEscrowModalOpen(false);
              }}
              className="w-full py-3 rounded-2xl bg-gradient-to-r from-purple-500 to-indigo-600 text-white font-tech font-bold text-xs uppercase tracking-wider shadow-md hover:opacity-90 transition-all"
            >
              Firmar Contrato y Depositar en Custodia
            </button>
          </div>
        </div>
      )}

      {/* 📦 3. MODAL COMPROBADOR DE IMPRIMIBILIDAD 3D & G-CODE */}
      {isGCodeModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
          <div className="relative w-full max-w-lg bg-cyber-900 border border-cyan-500/50 rounded-3xl p-6 shadow-cyber-card text-white space-y-4">
            <button
              onClick={() => setIsGCodeModalOpen(false)}
              className="absolute top-5 right-5 p-2 text-slate-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-cyan-500/20 text-cyan-300 border border-cyan-500">
                <FileCode className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-tech font-bold text-lg">REBANADOR 3D & GENERADOR G-CODE</h3>
                <p className="text-xs text-slate-400">Manufactura Aditiva FDM / Resina SLA</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-2 text-xs font-mono">
              <div className="p-3 rounded-xl bg-cyber-950 border border-cyber-800">
                <span className="text-slate-400 block text-[10px]">Altura de Capa:</span>
                <span className="text-cyan-300 font-bold">0.20 mm (Óptimo)</span>
              </div>
              <div className="p-3 rounded-xl bg-cyber-950 border border-cyber-800">
                <span className="text-slate-400 block text-[10px]">Tiempo Estimado:</span>
                <span className="text-white font-bold">4h 18min</span>
              </div>
              <div className="p-3 rounded-xl bg-cyber-950 border border-cyber-800">
                <span className="text-slate-400 block text-[10px]">Consumo Filamento:</span>
                <span className="text-cyber-gold font-bold">142 gramos</span>
              </div>
              <div className="p-3 rounded-xl bg-cyber-950 border border-cyber-800">
                <span className="text-slate-400 block text-[10px]">Imprimibilidad:</span>
                <span className="text-emerald-400 font-bold">100% Sin Errores</span>
              </div>
            </div>

            <button
              onClick={() => {
                const gcodeSample = `; G-Code generated by Aether Synergy 3D Slicer Engine\nG28 ; Home all axes\nM104 S210 ; Set Extruder Temp\nM140 S60 ; Set Bed Temp\nG1 Z0.2 F1200 ; Layer 1\n; Total Layers: 480\n; Ready for printing`;
                const blob = new Blob([gcodeSample], { type: 'text/plain;charset=utf-8' });
                const link = document.createElement('a');
                link.href = URL.createObjectURL(blob);
                link.download = `Aether_Model_${Date.now()}.gcode`;
                link.click();
              }}
              className="w-full py-3 rounded-2xl bg-cyan-500 hover:bg-cyan-400 text-black font-tech font-bold text-xs uppercase tracking-wider shadow-[0_0_15px_rgba(6,182,212,0.4)] transition-all flex items-center justify-center gap-2"
            >
              <Download className="w-4 h-4" />
              <span>Descargar Archivo .GCODE Rebanado</span>
            </button>
          </div>
        </div>
      )}

      {/* 🚚 4. MODAL COTIZADOR DE ENVÍOS INTERNACIONALES & ADUANAS (DHL / FEDEX) */}
      {isFreightModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
          <div className="relative w-full max-w-lg bg-cyber-900 border border-amber-500/50 rounded-3xl p-6 shadow-cyber-card text-white space-y-4">
            <button
              onClick={() => setIsFreightModalOpen(false)}
              className="absolute top-5 right-5 p-2 text-slate-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-amber-500/20 text-amber-300 border border-amber-500">
                <Truck className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-tech font-bold text-lg">COTIZADOR LOGÍSTICO & ADUANAS (DHL / FEDEX)</h3>
                <p className="text-xs text-slate-400">Origen: {activeSupplier.name} ({activeSupplier.country})</p>
              </div>
            </div>

            {/* Country Selector & Mode */}
            <div className="space-y-3 text-xs">
              <div>
                <label className="text-slate-300 font-bold block mb-1">País de Destino / Aduana:</label>
                <select
                  value={destinationCountry}
                  onChange={(e) => setDestinationCountry(e.target.value)}
                  className="w-full bg-cyber-950 border border-cyber-700 rounded-xl px-3 py-2 text-white text-xs focus:outline-none focus:border-amber-400"
                >
                  <option value="Estados Unidos (US)">🇺🇸 Estados Unidos (US) • Arancel HTS 6201: 6.2%</option>
                  <option value="México (MX)">🇲🇽 México (MX) • T-MEC Arancel Preferencial: 0.0%</option>
                  <option value="España / Unión Europea (EU)">🇪🇺 España / Unión Europea • TARIC: 12.0%</option>
                  <option value="Colombia (CO)">🇨🇴 Colombia (CO) • Arancel Dian: 15.0%</option>
                  <option value="Reino Unido (UK)">🇬🇧 Reino Unido (UK) • UK Global Tariff: 12.0%</option>
                </select>
              </div>

              {/* Shipping Method */}
              <div className="grid grid-cols-2 gap-2">
                <button
                  type="button"
                  onClick={() => setShippingMethod('air')}
                  className={`p-2.5 rounded-xl border text-xs font-bold flex items-center justify-center gap-1.5 transition-all ${
                    shippingMethod === 'air'
                      ? 'bg-amber-400 text-black border-amber-400 shadow-gold-glow'
                      : 'bg-cyber-950 border-cyber-800 text-slate-400'
                  }`}
                >
                  <Plane className="w-4 h-4" />
                  <span>DHL Express Aéreo (3-5 Días)</span>
                </button>

                <button
                  type="button"
                  onClick={() => setShippingMethod('sea')}
                  className={`p-2.5 rounded-xl border text-xs font-bold flex items-center justify-center gap-1.5 transition-all ${
                    shippingMethod === 'sea'
                      ? 'bg-amber-400 text-black border-amber-400 shadow-gold-glow'
                      : 'bg-cyber-950 border-cyber-800 text-slate-400'
                  }`}
                >
                  <Truck className="w-4 h-4" />
                  <span>Flete Marítimo FCL (22-28 Días)</span>
                </button>
              </div>

              {/* Calculations Grid */}
              <div className="p-3.5 rounded-2xl bg-cyber-950 border border-cyber-800 space-y-2 font-mono text-xs text-slate-300">
                <div className="flex justify-between">
                  <span className="text-slate-400">Peso Volumétrico ({orderQuantity}u):</span>
                  <span className="text-white font-bold">{(orderQuantity * 0.45).toFixed(1)} kg</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Flete Internacional Estimado:</span>
                  <span className="text-amber-400 font-bold">
                    ${shippingMethod === 'air' ? (orderQuantity * 4.2).toFixed(2) : (orderQuantity * 1.6).toFixed(2)} USD
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Estimación Impuestos & DUA Aduana:</span>
                  <span className="text-emerald-400 font-bold">${(grandTotalCost * 0.085).toFixed(2)} USD</span>
                </div>
                <div className="pt-2 border-t border-cyber-800 flex justify-between font-bold text-white text-sm">
                  <span>Costo Landed Total con Envío:</span>
                  <span className="text-amber-400">
                    ${(grandTotalCost + (shippingMethod === 'air' ? orderQuantity * 4.2 : orderQuantity * 1.6) + grandTotalCost * 0.085).toFixed(2)} USD
                  </span>
                </div>
              </div>
            </div>

            <button
              onClick={() => {
                alert(`¡Cotización logística formal para ${destinationCountry} vinculada a tu cuenta con tarifa garantizada por 14 días!`);
                setIsFreightModalOpen(false);
              }}
              className="w-full py-3 rounded-2xl bg-gradient-to-r from-amber-400 to-yellow-500 text-black font-tech font-bold text-xs uppercase tracking-wider shadow-gold-glow hover:opacity-90 transition-all"
            >
              Bloquear Tarifa Logística & Reservar Flete
            </button>
          </div>
        </div>
      )}

      {/* 🏷️ 5. MODAL PASAPORTE DIGITAL DE PRODUCTO (EU DPP 2026) */}
      {isDPPModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
          <div className="relative w-full max-w-lg bg-cyber-900 border border-emerald-500/50 rounded-3xl p-6 shadow-cyber-card text-white space-y-4">
            <button
              onClick={() => setIsDPPModalOpen(false)}
              className="absolute top-5 right-5 p-2 text-slate-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-emerald-500/20 text-emerald-300 border border-emerald-500">
                <Tag className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-tech font-bold text-lg">EU DIGITAL PRODUCT PASSPORT (DPP 2026)</h3>
                <p className="text-xs text-slate-400">Certificado Oficial de Trazabilidad & Cumplimiento Ecológico</p>
              </div>
            </div>

            {/* Passport Identity & QR */}
            <div className="p-4 rounded-2xl bg-cyber-950 border border-cyber-800 flex items-center gap-4">
              <div className="w-24 h-24 bg-white p-2 rounded-xl flex items-center justify-center shrink-0">
                <div className="w-full h-full border-2 border-dashed border-slate-900 rounded-lg flex flex-col items-center justify-center font-mono text-[8px] text-slate-900 font-bold text-center">
                  <Barcode className="w-8 h-8 text-slate-900 mb-0.5" />
                  <span>EU-DPP-2026</span>
                </div>
              </div>

              <div className="space-y-1 text-xs">
                <div className="font-mono text-emerald-400 font-bold text-[11px]">ID: DPP-AET-2026-EU-941</div>
                <div className="text-slate-300">Origen: {activeSupplier.name} ({activeSupplier.city}, {activeSupplier.country})</div>
                <div className="text-slate-400 text-[10px]">Blockchain Anchor: Polygon zkEVM • Hash #8f3d...a19</div>
              </div>
            </div>

            {/* Eco Metrics */}
            <div className="grid grid-cols-3 gap-2 text-center text-xs font-mono">
              <div className="p-2.5 rounded-xl bg-cyber-950 border border-cyber-800">
                <span className="text-slate-400 text-[10px] block">Huella Carbono</span>
                <span className="text-emerald-400 font-bold text-sm">3.4 kg CO₂e</span>
              </div>
              <div className="p-2.5 rounded-xl bg-cyber-950 border border-cyber-800">
                <span className="text-slate-400 text-[10px] block">Huella Hídrica</span>
                <span className="text-cyan-300 font-bold text-sm">420 Litros</span>
              </div>
              <div className="p-2.5 rounded-xl bg-cyber-950 border border-cyber-800">
                <span className="text-slate-400 text-[10px] block">Reciclabilidad</span>
                <span className="text-amber-400 font-bold text-sm">94.5%</span>
              </div>
            </div>

            <button
              onClick={() => {
                alert('¡Pasaporte Digital de Producto (EU DPP) exportado en PDF y enlazado a la etiqueta NFC/QR!');
                setIsDPPModalOpen(false);
              }}
              className="w-full py-3 rounded-2xl bg-gradient-to-r from-emerald-400 to-teal-500 text-black font-tech font-bold text-xs uppercase tracking-wider shadow-[0_0_15px_rgba(52,211,153,0.4)] hover:opacity-90 transition-all flex items-center justify-center gap-2"
            >
              <Download className="w-4 h-4" />
              <span>Descargar Certificado Oficial EU DPP (PDF)</span>
            </button>
          </div>
        </div>
      )}

      {/* INDUSTRIAL MULTILINGUAL TECH PACK MODAL */}
      {isTechPackModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 bg-black/90 backdrop-blur-md animate-fadeIn">
          <div className="relative bg-white text-slate-900 rounded-3xl w-full max-w-4xl shadow-2xl overflow-hidden flex flex-col max-h-[94vh]">
            {/* Subtle Confidential Watermark */}
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none opacity-[0.035] rotate-[-28deg] select-none z-0">
              <div className="text-center font-tech font-extrabold text-7xl text-slate-900 tracking-widest leading-none">
                AETHER SYNERGY <br />
                CONFIDENTIAL PRODUCTION TECH PACK <br />
                OFFICIAL B2B MANUFACTURING SPECIFICATION
              </div>
            </div>

            {/* Modal Header & Language Switcher */}
            <div className="relative z-10 p-4 sm:p-5 bg-slate-950 text-white flex flex-wrap items-center justify-between gap-3 border-b border-slate-800">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-2xl bg-amber-500/20 border border-amber-500 text-amber-400 shrink-0">
                  <FileText className="w-6 h-6" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-mono font-bold uppercase tracking-widest text-amber-400 bg-slate-900 px-2 py-0.5 rounded border border-slate-800">
                      DOC: {customSKU}
                    </span>
                    <span className="text-[10px] font-mono text-slate-400">{tPack.docRev}</span>
                  </div>
                  <h3 className="font-tech font-bold text-base sm:text-xl mt-0.5">
                    {tPack.docTitle}
                  </h3>
                </div>
              </div>

              {/* Controls: Edit Toggle + Multilingual Selector + Close */}
              <div className="flex flex-wrap items-center gap-2">
                <button
                  onClick={() => setIsEditing(!isEditing)}
                  className={`px-3 py-1 rounded-xl text-xs font-bold font-tech flex items-center gap-1.5 transition-all border ${
                    isEditing
                      ? 'bg-emerald-500 text-black border-emerald-400 shadow-md'
                      : 'bg-slate-900 hover:bg-slate-800 text-amber-400 border-amber-500/50'
                  }`}
                >
                  {isEditing ? <Save className="w-3.5 h-3.5" /> : <Edit3 className="w-3.5 h-3.5" />}
                  <span>{isEditing ? tPack.saveBtn : tPack.editBtn}</span>
                </button>

                <div className="flex bg-slate-900 p-1 rounded-xl border border-slate-800 text-[11px] font-mono">
                  <button
                    onClick={() => setTechPackLang('en')}
                    className={`px-2 py-0.5 rounded-lg transition-all ${
                      techPackLang === 'en' ? 'bg-amber-500 text-black font-bold' : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    🇺🇸 EN
                  </button>
                  <button
                    onClick={() => setTechPackLang('pt')}
                    className={`px-2 py-0.5 rounded-lg transition-all ${
                      techPackLang === 'pt' ? 'bg-amber-500 text-black font-bold' : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    🇵🇹 PT
                  </button>
                  <button
                    onClick={() => setTechPackLang('tr')}
                    className={`px-2 py-0.5 rounded-lg transition-all ${
                      techPackLang === 'tr' ? 'bg-amber-500 text-black font-bold' : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    🇹🇷 TR
                  </button>
                  <button
                    onClick={() => setTechPackLang('it')}
                    className={`px-2 py-0.5 rounded-lg transition-all ${
                      techPackLang === 'it' ? 'bg-amber-500 text-black font-bold' : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    🇮🇹 IT
                  </button>
                  <button
                    onClick={() => setTechPackLang('es')}
                    className={`px-2 py-0.5 rounded-lg transition-all ${
                      techPackLang === 'es' ? 'bg-amber-500 text-black font-bold' : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    🇨🇴 ES
                  </button>
                </div>

                <button
                  onClick={() => setIsTechPackModalOpen(false)}
                  className="p-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Modal Body */}
            <div className="relative z-10 p-4 sm:p-6 overflow-y-auto space-y-6 text-xs font-sans">
              {/* Product Header & Commercial Summary */}
              <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 p-4 bg-slate-50 border border-slate-200 rounded-2xl">
                <div>
                  <span className="text-slate-500 font-bold uppercase block text-[10px]">
                    {tPack.styleLabel}
                  </span>
                  {isEditing ? (
                    <input
                      type="text"
                      value={customStyleName}
                      onChange={(e) => setCustomStyleName(e.target.value)}
                      className="w-full bg-white border border-amber-500 rounded p-1 text-xs font-bold text-slate-900"
                    />
                  ) : (
                    <span className="font-bold text-slate-900 text-sm">{customStyleName}</span>
                  )}
                </div>

                <div>
                  <span className="text-slate-500 font-bold uppercase block text-[10px]">
                    {tPack.factoryLabel}
                  </span>
                  <span className="font-bold text-slate-900 text-sm">{activeSupplier.name} ({activeSupplier.country})</span>
                </div>

                <div>
                  <span className="text-slate-500 font-bold uppercase block text-[10px]">
                    {tPack.volumeLabel}
                  </span>
                  <span className="font-bold text-slate-900 text-sm">{orderQuantity} units</span>
                </div>

                <div>
                  <span className="text-slate-500 font-bold uppercase block text-[10px]">
                    {tPack.pantoneLabel}
                  </span>
                  <div className="flex items-center gap-1.5 mt-0.5">
                    <span className="w-3.5 h-3.5 rounded-full bg-[#1E293B] border border-slate-400" />
                    <span className="w-3.5 h-3.5 rounded-full bg-[#E5A93C] border border-slate-400" />
                    <span className="text-[11px] font-mono font-bold text-slate-700">19-4007 / 14-0848</span>
                  </div>
                </div>
              </div>

              {/* 1. Sizing Table with Dual Units (cm and inches) */}
              <div className="space-y-2">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <h4 className="font-tech font-bold text-sm text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
                    <Ruler className="w-4 h-4 text-amber-600" /> {tPack.gradingTitle}
                  </h4>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-mono text-slate-500">{tPack.tolerance}</span>
                    <div className="flex bg-slate-200 p-0.5 rounded-lg text-[10px] font-mono font-bold">
                      <button onClick={() => setUnitSystem('both')} className={`px-2 py-0.5 rounded ${unitSystem === 'both' ? 'bg-white text-slate-900 shadow' : 'text-slate-600'}`}>Dual</button>
                      <button onClick={() => setUnitSystem('cm')} className={`px-2 py-0.5 rounded ${unitSystem === 'cm' ? 'bg-white text-slate-900 shadow' : 'text-slate-600'}`}>CM</button>
                      <button onClick={() => setUnitSystem('in')} className={`px-2 py-0.5 rounded ${unitSystem === 'in' ? 'bg-white text-slate-900 shadow' : 'text-slate-600'}`}>IN</button>
                    </div>
                  </div>
                </div>

                <div className="overflow-x-auto border border-slate-300 rounded-2xl shadow-sm">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-slate-900 text-white font-tech uppercase text-[11px]">
                      <tr>
                        <th className="p-3">{tPack.pomHeader}</th>
                        <th className="p-3 text-center">S</th>
                        <th className="p-3 text-center">{tPack.baseSample}</th>
                        <th className="p-3 text-center">L</th>
                        <th className="p-3 text-center">XL</th>
                        <th className="p-3 text-center">XXL</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-200 text-slate-800">
                      <tr className="hover:bg-slate-50">
                        <td className="p-3 font-semibold">{tPack.chest}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '22.0 in' : unitSystem === 'cm' ? '56.0 cm' : '56 cm / 22.0"'}</td>
                        <td className="p-3 text-center font-mono font-bold bg-amber-50 text-amber-900">{unitSystem === 'in' ? '22.8 in' : unitSystem === 'cm' ? '58.0 cm' : '58 cm / 22.8"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '24.0 in' : unitSystem === 'cm' ? '61.0 cm' : '61 cm / 24.0"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '25.2 in' : unitSystem === 'cm' ? '64.0 cm' : '64 cm / 25.2"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '26.4 in' : unitSystem === 'cm' ? '67.0 cm' : '67 cm / 26.4"'}</td>
                      </tr>
                      <tr className="hover:bg-slate-50">
                        <td className="p-3 font-semibold">{tPack.length}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '26.8 in' : unitSystem === 'cm' ? '68.0 cm' : '68 cm / 26.8"'}</td>
                        <td className="p-3 text-center font-mono font-bold bg-amber-50 text-amber-900">{unitSystem === 'in' ? '27.5 in' : unitSystem === 'cm' ? '70.0 cm' : '70 cm / 27.5"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '28.7 in' : unitSystem === 'cm' ? '73.0 cm' : '73 cm / 28.7"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '29.9 in' : unitSystem === 'cm' ? '76.0 cm' : '76 cm / 29.9"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '31.1 in' : unitSystem === 'cm' ? '79.0 cm' : '79 cm / 31.1"'}</td>
                      </tr>
                      <tr className="hover:bg-slate-50">
                        <td className="p-3 font-semibold">{tPack.sleeve}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '25.2 in' : unitSystem === 'cm' ? '64.0 cm' : '64 cm / 25.2"'}</td>
                        <td className="p-3 text-center font-mono font-bold bg-amber-50 text-amber-900">{unitSystem === 'in' ? '26.0 in' : unitSystem === 'cm' ? '66.0 cm' : '66 cm / 26.0"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '26.8 in' : unitSystem === 'cm' ? '68.0 cm' : '68 cm / 26.8"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '27.5 in' : unitSystem === 'cm' ? '70.0 cm' : '70 cm / 27.5"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '28.3 in' : unitSystem === 'cm' ? '72.0 cm' : '72 cm / 28.3"'}</td>
                      </tr>
                      <tr className="hover:bg-slate-50">
                        <td className="p-3 font-semibold">{tPack.hem}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '20.5 in' : unitSystem === 'cm' ? '52.0 cm' : '52 cm / 20.5"'}</td>
                        <td className="p-3 text-center font-mono font-bold bg-amber-50 text-amber-900">{unitSystem === 'in' ? '21.2 in' : unitSystem === 'cm' ? '54.0 cm' : '54 cm / 21.2"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '22.4 in' : unitSystem === 'cm' ? '57.0 cm' : '57 cm / 22.4"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '23.6 in' : unitSystem === 'cm' ? '60.0 cm' : '60 cm / 23.6"'}</td>
                        <td className="p-3 text-center font-mono">{unitSystem === 'in' ? '24.8 in' : unitSystem === 'cm' ? '63.0 cm' : '63 cm / 24.8"'}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              {/* 2. Commercial FAQ, Incoterms & Payment Terms */}
              <div className="space-y-2">
                <h4 className="font-tech font-bold text-sm text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
                  <HelpCircle className="w-4 h-4 text-amber-600" /> {tPack.commercialTitle}
                </h4>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                  <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl space-y-1">
                    <span className="font-bold text-slate-900 block">{tPack.incotermLabel}</span>
                    <p className="text-slate-600">{tPack.incotermDesc}</p>
                  </div>

                  <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl space-y-1">
                    <span className="font-bold text-slate-900 block">{tPack.paymentLabel}</span>
                    <p className="text-slate-600">{tPack.paymentDesc}</p>
                  </div>

                  <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl space-y-1">
                    <span className="font-bold text-slate-900 block">{tPack.ppsLabel}</span>
                    <p className="text-slate-600">{tPack.ppsDesc}</p>
                  </div>
                </div>
              </div>

              {/* 3. Detailed BOM & Stitching */}
              <div className="space-y-2">
                <h4 className="font-tech font-bold text-sm text-slate-900 uppercase tracking-wider flex items-center gap-1.5">
                  <Tag className="w-4 h-4 text-amber-600" /> {tPack.bomTitle}
                </h4>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                  <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl space-y-1">
                    <span className="font-bold text-slate-900 block">{tPack.shellLabel}</span>
                    <p className="text-slate-600">{tPack.shellDesc}</p>
                  </div>

                  <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl space-y-1">
                    <span className="font-bold text-slate-900 block">{tPack.zipperLabel}</span>
                    <p className="text-slate-600">{tPack.zipperDesc}</p>
                  </div>

                  <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl space-y-1">
                    <span className="font-bold text-slate-900 block">{tPack.stitchLabel}</span>
                    <p className="text-slate-600">{tPack.stitchDesc}</p>
                  </div>

                  <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl space-y-1">
                    <span className="font-bold text-slate-900 block">{tPack.careLabel}</span>
                    <p className="text-slate-600">{tPack.careDesc}</p>
                  </div>
                </div>
              </div>

              {/* 4. Formal Signatures & Approvals */}
              <div className="p-4 bg-slate-900 text-white rounded-2xl space-y-4 text-xs">
                <div className="flex items-center justify-between">
                  <span className="font-tech font-bold text-amber-400 uppercase flex items-center gap-1.5">
                    <PenTool className="w-4 h-4" /> {tPack.signaturesTitle}
                  </span>
                  <span className="font-mono text-[10px] text-slate-400">SKU: {customSKU}</span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 pt-2">
                  <div className="border-t border-slate-700 pt-2 text-left">
                    <span className="font-bold block text-slate-200">{tPack.brandSig}</span>
                    <span className="text-[11px] text-slate-400 font-mono">{tPack.signDate}</span>
                  </div>
                  <div className="border-t border-slate-700 pt-2 text-left">
                    <span className="font-bold block text-slate-200">{tPack.factorySig}</span>
                    <span className="text-[11px] text-slate-400 font-mono">{tPack.signDate}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="relative z-10 p-4 bg-slate-100 border-t border-slate-200 flex flex-wrap items-center justify-between gap-3">
              <span className="text-slate-500 text-[11px] font-mono">
                {tPack.footerNotice}
              </span>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => window.print()}
                  className="px-5 py-2.5 rounded-2xl bg-slate-950 hover:bg-slate-800 text-white font-tech font-bold text-xs uppercase tracking-wider flex items-center gap-2 shadow-md transition-all"
                >
                  <Printer className="w-4 h-4 text-amber-400" />
                  <span>{tPack.printBtn}</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
